# Copyright (c) 2026 The Regents of the University of California
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

if not env['CONF'].get('USE_APPLE_VIRT', False):
    Return()

env.Append(LINKFLAGS=['-framework', 'Hypervisor'])

env.TagImplies('apple_virt', 'gem5 lib')
env.TagImplies(env.subst('${CONF["APPLE_VIRT_ISA"]} apple_virt'),
               env.subst('${CONF["APPLE_VIRT_ISA"]} isa'))

SimObject('AppleVirtVM.py', sim_objects=['AppleVirtVM'], tags=['apple_virt'])
SimObject(
    'BaseAppleVirtCPU.py',
    sim_objects=['BaseAppleVirtCPU'],
    tags=['apple_virt'],
)

Source('vm.cc', tags=['apple_virt'])
Source('base.cc', tags=['apple_virt'])

DebugFlag(
    'AppleVirt',
    'Apple virtualization backend diagnostics',
    tags=['apple_virt'],
)
DebugFlag('AppleVirtRun', 'HVF run-loop tracing', tags=['apple_virt'])

CompoundFlag('AppleVirtAll', ['AppleVirt', 'AppleVirtRun'],
             'All Apple virtualization debug flags', tags=['apple_virt'])
