"""
This module contains BUILD macros for generating C++ code from SLICC files
within the gem5 Ruby cache model.

It includes rules for:
-   `generate_shared_slicc`: Processing shared SLICC interface files.
-   `gem5_slicc_cc_library`: Generating a C++ library from a specific SLICC protocol definition.
-   `generate_imported_headers`: Creating necessary stub headers for external Ruby components.
"""

load("@rules_python//python:defs.bzl", "py_library")
load("//bazel:rules.bzl", "gem5_cc_library", "gem5_sim_object", "to_snake_case")

# This is the path relative to the current package that the generated files will be in.
# It must be what other files use to include these files (e.g., `#include "mem/ruby/protocol/...`)
# files use to include these files (e.g., `#include "mem/ruby/protocol/...`)
_protocol_gen_path = ""

def generate_shared_slicc(name, slicc_files, sm_srcs, protocol_outs, exported_headers, deps = []):
    """Generates a cc_library target for shared gem5 Slicc C++ interfaces.

    This macro processes common SLICC files (like RubySlicc_interfaces.slicc)
    that define types and utilities used across different Ruby protocols.

    Args:
        name: The name of the rule.
        slicc_files: A list of .slicc files defining the shared interfaces.
        sm_srcs: A list of .sm source files required by the slicc_files.
        protocol_outs: A list of expected output files (.cc and .hh) generated by slicc.
        exported_headers: A list of dicts, where each dict specifies a generated header
                          and its dependencies, to be exposed as separate gem5_cc_library targets.
                          These are used by libraries in Ruby outside of the protocol directory.
        deps: Additional dependencies for the generated cc_library.
    """

    tool_binary = "//bazel/build_tools:build_slicc"

    # The genrule needs access to all .sm files and all .slicc files.
    genrule_srcs = sm_srcs + slicc_files

    # Output path relative to the current package this is required for the include paths to work.
    qualified_outs = [out for out in protocol_outs]

    genrule_name = "_" + name + "_gen"

    # Run the slicc tool and generate the cc and hh files.
    native.genrule(
        name = genrule_name,
        srcs = genrule_srcs,
        outs = qualified_outs,
        cmd = """            set -e
            TEMP_DIR=$$(mktemp -d)
            $(location {tool_binary}) \
                -C $$TEMP_DIR \
                --cc_includes='mem/ruby/slicc_interface/RubySlicc_includes.hh' \
                {include_args}
            cp -r $$TEMP_DIR/* $(RULEDIR)/
            rm -rf $$TEMP_DIR
            """.format(
            tool_binary = tool_binary,
            protocol_gen_path = _protocol_gen_path,
            include_args = " ".join(["$(location %s)" % slicc for slicc in slicc_files]),
        ),
        tools = [tool_binary],
    )

    generated_srcs = [out for out in qualified_outs if out.endswith(".cc")]
    generated_hdrs = [out for out in qualified_outs if out.endswith(".hh")]

    # Generate separate cc_library targets for the exported headers.
    for header in exported_headers:
        gem5_cc_library(
            name = header["header"].split(".")[0] + "_hh",
            hdrs = [header["header"]],
            includes = ["."],
            deps = header["deps"],
        )

    # Generate the main cc_library target for the generated files.
    # This should be used by the protocols.
    gem5_cc_library(
        name = name,
        srcs = generated_srcs,
        hdrs = generated_hdrs,
        includes = ["."],
        deps = deps,
    )

def gem5_slicc_cc_library(name, protocol_path, slicc_includes, sm_srcs, protocol_outs, exported_headers = [], cc_deps = [], cc_deps_no_header = [], sim_object_py_deps = [], sim_object_param_deps = [], python_module_prefix = "src.mem.ruby.protocol"):
    """Generates a cc_library target for a gem5 Slicc C++ library.

    This macro processes a single SLICC protocol definition, generating C++ and Python code
    for the protocol's classes and utilities. It also creates `gem5_sim_object_generator` targets
    for each generated SimObject, allowing them to be used in Python code.
    Targets generated by this macro include:
        - name: A gem5_cc_library target for the generated C++ files.
        - name + "_headers": A gem5_cc_library target for the generated C++ headers.
        - param_<ControllerName>_hh: A gem5_sim_object_generator target for the generated SimObject.
        - <ControllerName>_py: A py_library target for the generated SimObject.

    Args:
        name: The name of the rule (e.g., the name of the protocol, like "MESI_Two_Level").
        protocol_path: The main .slicc file for the protocol (e.g., MESI_Two_Level.slicc).
                       This is passed to build_slicc's --protocol argument.
        slicc_includes: A list of ALL .slicc files to be passed to build_slicc's --includes argument.
        sm_srcs: A list of all the .sm source files required by the .slicc files listed
                 in slicc_includes. This forms the main data srcs for the genrule.
        protocol_outs: A list of expected output files (.cc, .hh, .py) generated by slicc.
                       These should be the filenames, not including the PROTOCOL/ directory.
        exported_headers: A list of dicts, where each dict specifies a generated header
                          and its dependencies, to be exposed as separate gem5_cc_library targets.
                          These are used by libraries in Ruby outside of the protocol directory.
        cc_deps: Dependencies for the generated cc_library.
        cc_deps_no_header: Dependencies for the generated cc_library. NOT INCLUDED IN THE HEADER TARGET.
                           This is used to avoid dependency cycles. Put cc dependencies that have
                           dependencies on the generated headers here.
        sim_object_py_deps: Dependencies for the generated py_library targets for the SimObjects.
        sim_object_param_deps: Extra parameter dependencies for the gem5_sim_object_generator.
        python_module_prefix: The prefix for the python module path for the generated SimObjects.
                              This should be the "location" of current package.
    """

    tool_binary = "//bazel/build_tools:build_slicc"

    # The genrule needs access to all .sm files and all .slicc files.
    # We explicitly include protocol_path in slicc_includes, but keep it separate
    # here as it's passed as a distinct argument to build_slicc.
    genrule_srcs = sm_srcs + slicc_includes + [protocol_path]

    # Output path relative to the current package. This is required for the include paths to work.
    # Python files, on the other hand, should be generated in the current package.
    qualified_outs = []
    for out in protocol_outs:
        if out.endswith(".py"):
            qualified_outs.append(out)
        else:
            qualified_outs.append(name + "/" + out)

    genrule_name = "_" + name + "_gen"

    # Run the slicc tool and generate the cc, hh, and py files.
    # Move the python files to the ruledir so we can use
    # import src.mem.ruby.protocol.<protocol>.<file>
    native.genrule(
        name = genrule_name,
        srcs = genrule_srcs,
        outs = qualified_outs,
        cmd = """            set -e
            TEMP_DIR=$$(mktemp -d)
            $(location {tool_binary}) \
                -C $$TEMP_DIR \
                --protocol='$(location {protocol_path})' \
                --includes='{include_args}' \
                --cc_includes='mem/ruby/slicc_interface/RubySlicc_includes.hh'
            
            # Match the output structure generated by SLICC
            # cp -r will preserve the {name}/ subdirectory for C++ and others
            cp -r $$TEMP_DIR/* $(RULEDIR)/
            
            # Flatten Python files if they are in the protocol subdirectory
            if [ -d "$(RULEDIR)/{name}" ]; then
              # Move .py files to the base protocol directory
              mv $(RULEDIR)/{name}/*.py $(RULEDIR)/ 2>/dev/null || true
              # Explicitly remove any remaining .py files or __init__.py in the subdirectory
              # to avoid import name collisions (e.g., CHI.CHI)
              rm -f $(RULEDIR)/{name}/__init__.py 2>/dev/null || true
              rm -f $(RULEDIR)/{name}/*.py 2>/dev/null || true
            fi
            
            rm -rf $$TEMP_DIR
            """.format(
            tool_binary = tool_binary,
            protocol_path = protocol_path,
            include_args = ",".join(["$(location %s)" % slicc for slicc in slicc_includes]),
            name = name,
        ),
        tools = [tool_binary],
    )

    generated_srcs = [out for out in qualified_outs if out.endswith(".cc")]
    generated_hdrs = [out for out in qualified_outs if out.endswith(".hh")]
    generated_py = [out for out in qualified_outs if out.endswith(".py")]

    param_headers = []

    # Generate python libraries for each generated python file and declare the sim_objects.
    for py_file in generated_py:
        if py_file.endswith("__init__.py"):
            continue

        # The python files are in a subdirectory and called <name>.py.
        sim_object_name = py_file.split("/")[-1].split(".")[0]
        param_headers.append(":" + to_snake_case(sim_object_name) + "_sim_object")
        py_library(
            name = sim_object_name + "_py",
            srcs = [py_file],
            visibility = ["//visibility:public"],
            deps = sim_object_py_deps + ["//src/mem/ruby/protocol:protocol_init"],
        )

        gem5_sim_object(
            name = to_snake_case(sim_object_name) + "_sim_object",
            extra_param_deps = sim_object_param_deps,
            # These are hardcoded, but should never change unless the slicc language changes.
            extra_tool_deps = [
                "//src/python/m5/util",
                "//src/python/m5:defines",
            ],
            sim_object_name = sim_object_name,
            sim_object_py_lib = ":" + sim_object_name + "_py",
            sim_object_header = ":" + name,
            sim_object_module = python_module_prefix + "." + sim_object_name,
        )

    for header in exported_headers:
        gem5_cc_library(
            name = header["header"].split(".")[0] + "_hh",
            hdrs = [name + "/" + header["header"]],
            includes = ["."],
            deps = header["deps"],
        )

    # This is the main cc_library target for the generated files. This is what other parts of the
    # code will use to include the generated files.
    gem5_cc_library(
        name = name,
        srcs = generated_srcs,
        hdrs = generated_hdrs,
        includes = ["."],
        copts = ["-Wno-parentheses-equality", "-fexceptions"],  # There are exceptions in the generated code.
        features = ["-use_header_modules"],
        deps = cc_deps + param_headers + cc_deps_no_header,
    )

def generate_imported_headers(name, imported_headers):
    """Generates stub headers for external Ruby components used by SLICC.

    The SLICC-generated code expects to include certain headers from other parts
    of Ruby using paths like `#include "mem/ruby/protocol/HEADER.hh"`. Since these
    headers are defined outside the current package, this macro creates simple
    stub .hh files in the protocol directory that simply include the actual
    header from its true location.

    Args:
        name: The name of the rule.
        imported_headers: A list of labels for gem5_cc_library targets whose
                          headers need to be made available to SLICC-generated code.
    """

    all_headers = []
    all_deps = []
    for header in imported_headers:
        header_name = header.split(":")[1] + "_hh"
        include_path = header[2:].replace(":", "/") + ".hh"
        header_path = header.split(":")[1] + ".hh"
        all_headers.append(header_path)
        all_deps.append(header + "_hh")

        native.genrule(
            name = "_" + name + "_" + header_name,
            outs = [header_path],
            cmd = "echo '#include \"{include_path}\"' > $@".format(include_path = include_path),
        )

        gem5_cc_library(
            name = header_name,
            hdrs = [header_path],
            includes = ["."],
            deps = [header + "_hh"],
        )

    # This is the main cc_library target for the generated files. This can be used by the protocol
    # code to access the imported headers for convience.
    gem5_cc_library(
        name = name,
        hdrs = all_headers,
        includes = ["."],
        deps = all_deps,
    )

default_sim_object_py_deps = [
    "//src/python/m5/params",
    "//src/python/m5/objects:Controller",
    "//src/python/m5/objects:Sequencer",
    "//src/python/m5/objects:MessageBuffer",
    "//src/python/m5/objects:RubyPrefetcher",
    "//src/python/m5/objects:DirectoryMemory",
    "//src/python/m5/objects:Prefetcher",
    "//src/python/m5/objects:RubyCache",
    "//src/python/m5/objects:WireBuffer",
    "//src/python/m5:SimObject",
]

default_sim_object_param_deps = [
    "//src/mem/ruby/system:dma_sequencer_sim_object",
    "//src/mem/cache/prefetch:base_prefetcher_sim_object",
    "//src/mem/ruby/system:ruby_sequencer_sim_object",
    "//src/mem/ruby/structures:ruby_cache_sim_object",
    "//src/mem/ruby/structures:ruby_prefetcher_sim_object",
    "//src/mem/ruby/structures:ruby_directory_memory_sim_object",
    "//src/mem/ruby/system:ruby_htm_sequencer_sim_object",
    "//src/mem/ruby/network:message_buffer_sim_object",
    "//src/mem/ruby/slicc_interface:ruby_controller_sim_object",
    "//src/sim:sim_object",
    "//src/mem/cache/prefetch:base",
    "//src/mem/ruby/network:MessageBuffer_hh",
    "//src/mem/ruby/structures:CacheMemory_hh",
    "//src/mem/ruby/structures:DirectoryMemory_hh",
    "//src/mem/ruby/structures:RubyPrefetcher_hh",
    "//src/mem/ruby/system:DMASequencer_hh",
    "//src/mem/ruby/system:Sequencer_hh",
]

default_protocol_cc_deps = [
    "//src/mem/ruby/protocol:imported_headers",
    "//src/mem/ruby/protocol:shared",
    "//src/base:compiler",
    "//src/base:cprintf",
    "//src/base:logging",
    "//src/base:trace",
    "//src/mem/ruby:debug_ProtocolTrace",
    "//src/mem/ruby:debug_RubyGenerated",
    "//src/mem/ruby:debug_RubySlicc",
    "//src/mem/ruby/common",
    "//src/mem/ruby/network:MessageBuffer_hh",
    "//src/mem/ruby/network:Network",
    "//src/mem/ruby/slicc_interface:AbstractController_hh",
    "//src/mem/ruby/slicc_interface:ProtocolInfo",
    "//src/mem/ruby/slicc_interface:RubySlicc_Util",
    "//src/mem/ruby/slicc_interface:RubySlicc_includes",
    "//src/mem/ruby/structures:DirectoryMemory_hh",
    "//src/mem/ruby/system:RubySystem_hh",
    "//src/sim:sim_object",
]
