# $Id: Makefile,v 1.1.1.1 1997/10/30 23:27:13 verghese Exp $
# $Log: Makefile,v $
# Revision 1.1.1.1  1997/10/30 23:27:13  verghese
# current 10/29/97
#
# Revision 1.2  1994/06/28  20:08:21  fdh
# Modified filenames and build precedure to fit into a FAT filesystem.
#
# Revision 1.1  1994/03/11  05:14:12  fdh
# Initial revision
#

include ../rules.osf

all:

clean:
	rm -f *~ \#*\# core
	$(CLEAN)

