load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "x11keysym",
    hdrs = [
        "keysym.h",
        "keysymdef.h",
    ],
    include_prefix = "x11keysym",
)
