"""Repository rule to auto-detect system Python headers.

gem5 embeds a Python interpreter, so it needs the system Python headers
(Python.h, etc.) at compile time. This rule detects the Python include path
using sysconfig and makes the headers available as a cc_library.
"""

def _system_python_impl(repository_ctx):
    python3 = repository_ctx.which("python3")
    if not python3:
        fail("python3 not found in PATH. Install Python 3 development headers.")

    # Get the Python include path via sysconfig
    result = repository_ctx.execute([
        str(python3),
        "-c",
        "import sysconfig; print(sysconfig.get_path('include'))",
    ])
    if result.return_code != 0:
        fail("Failed to detect Python include path: " + result.stderr)
    include_path = result.stdout.strip()

    # Get Python version
    ver_result = repository_ctx.execute([
        str(python3),
        "-c",
        "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))",
    ])
    python_version = ver_result.stdout.strip() if ver_result.return_code == 0 else "unknown"

    # Get Python library path for linking
    lib_result = repository_ctx.execute([
        str(python3),
        "-c",
        "import sysconfig; print(sysconfig.get_config_var('LIBDIR') or '')",
    ])
    lib_path = lib_result.stdout.strip() if lib_result.return_code == 0 else ""

    # Symlink the Python include directory
    repository_ctx.symlink(include_path, "include")

    # Generate BUILD file
    linkopts_entries = ['        "-lpython{version}",'.format(version = python_version)]
    if lib_path:
        linkopts_entries.append('        "-L{lib_path}",'.format(lib_path = lib_path))
    linkopts_block = "\n".join(linkopts_entries)

    repository_ctx.file("BUILD.bazel", content = """\
# Auto-generated by python_detect.bzl -- do not edit.
# Detected Python {version} headers at: {path}
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = glob(["include/**"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "python",
    deps = [":headers"],
    linkopts = [
{linkopts}
    ],
    visibility = ["//visibility:public"],
)
""".format(version = python_version, path = include_path, linkopts = linkopts_block))

    # Write version info for use by other rules
    repository_ctx.file("version.bzl", content = """\
# Auto-generated by python_detect.bzl -- do not edit.
PYTHON_VERSION = "{version}"
""".format(version = python_version))

system_python = repository_rule(
    implementation = _system_python_impl,
    local = True,
    environ = ["PATH"],
    doc = "Detects system Python headers for gem5 embedded Python support.",
)
