"""Contains a list of gem5 SimObjects and their import information."""

SIM_OBJECTS = [
    {
        "mod_name": "SimpleObject",
        "module_path": "src.learning_gem5.part2.SimpleObject",
        "dep": "//src/learning_gem5/part2:SimpleObject_py",
        "simobjects": ["SimpleObject"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "HelloObject",
        "module_path": "src.learning_gem5.part2.HelloObject",
        "dep": "//src/learning_gem5/part2:HelloObject_py",
        "simobjects": ["HelloObject", "GoodbyeObject"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Root",
        "module_path": "src.sim.Root",
        "dep": "//src/sim:Root_py",
        "simobjects": ["Root"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ClockDomain",
        "module_path": "src.sim.ClockDomain",
        "dep": "//src/sim:ClockDomain_py",
        "simobjects": ["ClockDomain", "SrcClockDomain", "DerivedClockDomain"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VoltageDomain",
        "module_path": "src.sim.VoltageDomain",
        "dep": "//src/sim:VoltageDomain_py",
        "simobjects": ["VoltageDomain"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PowerState",
        "module_path": "src.sim.PowerState",
        "dep": "//src/sim:PowerState_py",
        "simobjects": ["PowerState"],
        "enums": ["PwrState"],
        "other_simobjects": [],
    },
    {
        "mod_name": "PowerDomain",
        "module_path": "src.sim.PowerDomain",
        "dep": "//src/sim:PowerDomain_py",
        "simobjects": ["PowerDomain"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SubSystem",
        "module_path": "src.sim.SubSystem",
        "dep": "//src/sim:SubSystem_py",
        "simobjects": ["SubSystem"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ClockedObject",
        "module_path": "src.sim.ClockedObject",
        "dep": "//src/sim:ClockedObject_py",
        "simobjects": ["ClockedObject"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PowerModelState",
        "module_path": "src.sim.power.PowerModelState",
        "dep": "//src/sim/power:PowerModelState_py",
        "simobjects": ["PowerModelState"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PowerModel",
        "module_path": "src.sim.power.PowerModel",
        "dep": "//src/sim/power:PowerModel_py",
        "simobjects": ["PowerModel"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ThermalModel",
        "module_path": "src.sim.power.ThermalModel",
        "dep": "//src/sim/power:ThermalModel_py",
        "simobjects": ["ThermalNode", "ThermalResistor", "ThermalCapacitor", "ThermalReference", "ThermalModel"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ThermalDomain",
        "module_path": "src.sim.power.ThermalDomain",
        "dep": "//src/sim/power:ThermalDomain_py",
        "simobjects": ["ThermalDomain"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Device",
        "module_path": "src.dev.Device",
        "dep": "//src/dev:Device_py",
        "simobjects": ["PioDevice", "BasicPioDevice", "IsaFake", "DmaDevice", "DmaVirtDevice"],
        "enums": [],
        "other_simobjects": ["BadAddr"],
    },
    {
        "mod_name": "Display",
        "module_path": "src.dev.arm.Display",
        "dep": "//src/dev/arm:Display_py",
        "simobjects": ["Display"],
        "enums": [],
        "other_simobjects": ["Display1080p"],
    },
    {
        "mod_name": "System",
        "module_path": "src.sim.System",
        "dep": "//src/sim:System_py",
        "simobjects": ["System"],
        "enums": ["MemoryMode"],
        "other_simobjects": [],
    },
    {
        "mod_name": "DVFSHandler",
        "module_path": "src.sim.DVFSHandler",
        "dep": "//src/sim:DVFSHandler_py",
        "simobjects": ["DVFSHandler"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "RedirectPath",
        "module_path": "src.sim.RedirectPath",
        "dep": "//src/sim:RedirectPath_py",
        "simobjects": ["RedirectPath"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Workload",
        "module_path": "src.sim.Workload",
        "dep": "//src/sim:Workload_py",
        "simobjects": ["Workload", "StubWorkload", "SEWorkload", "KernelWorkload"],
        "enums": ["KernelPanicOopsBehaviour"],
        "other_simobjects": [],
    },
    {
        "mod_name": "params",
        "module_path": "src.python.m5.params",
        "dep": "//src/python/m5/params",
        "simobjects": [],
        "enums": ["ByteOrder"],
        "other_simobjects": [],
    },
    {
        "mod_name": "AbstractMemory",
        "module_path": "src.mem.AbstractMemory",
        "dep": "//src/mem:AbstractMemory_py",
        "simobjects": ["AbstractMemory"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SimpleMemory",
        "module_path": "src.mem.SimpleMemory",
        "dep": "//src/mem:SimpleMemory_py",
        "simobjects": ["SimpleMemory"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseTLB",
        "module_path": "src.arch.generic.BaseTLB",
        "dep": "//src/arch/generic:BaseTLB_py",
        "simobjects": ["BaseTLB"],
        "enums": ["TypeTLB"],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseMMU",
        "module_path": "src.arch.generic.BaseMMU",
        "dep": "//src/arch/generic:BaseMMU_py",
        "simobjects": ["BaseMMU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseISA",
        "module_path": "src.arch.generic.BaseISA",
        "dep": "//src/arch/generic:BaseISA_py",
        "simobjects": ["BaseISA"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "InstDecoder",
        "module_path": "src.arch.generic.InstDecoder",
        "dep": "//src/arch/generic:InstDecoder_py",
        "simobjects": ["InstDecoder"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseCPU",
        "module_path": "src.cpu.BaseCPU",
        "dep": "//src/cpu:BaseCPU_py",
        "simobjects": ["BaseCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "DummyChecker",
        "module_path": "src.cpu.DummyChecker",
        "dep": "//src/cpu:DummyChecker_py",
        "simobjects": ["DummyChecker"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CheckerCPU",
        "module_path": "src.cpu.checker.CheckerCPU",
        "dep": "//src/cpu/checker:CheckerCPU_py",
        "simobjects": ["CheckerCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseMinorCPU",
        "module_path": "src.cpu.minor.BaseMinorCPU",
        "dep": "//src/cpu/minor:BaseMinorCPU_py",
        "simobjects": ["MinorOpClass", "MinorOpClassSet", "MinorFUTiming", "MinorFU", "MinorFUPool", "BaseMinorCPU"],
        "enums": ["ThreadPolicy"],
        "other_simobjects": [],
    },
    {
        "mod_name": "TimingExpr",
        "module_path": "src.cpu.TimingExpr",
        "dep": "//src/cpu:TimingExpr_py",
        "simobjects": ["TimingExpr", "TimingExprLiteral", "TimingExprSrcReg", "TimingExprLet", "TimingExprRef", "TimingExprUn", "TimingExprBin", "TimingExprIf"],
        "enums": ["TimingExprOp"],
        "other_simobjects": [],
    },
    {
        "mod_name": "InstTracer",
        "module_path": "src.sim.InstTracer",
        "dep": "//src/sim:InstTracer_py",
        "simobjects": ["InstTracer", "InstDisassembler"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CPUTracers",
        "module_path": "src.cpu.CPUTracers",
        "dep": "//src/cpu:CPUTracers_py",
        "simobjects": ["ExeTracer", "IntelTrace", "NativeTrace"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "XBar",
        "module_path": "src.mem.XBar",
        "dep": "//src/mem:XBar_py",
        "simobjects": ["BaseXBar", "NoncoherentXBar", "CoherentXBar", "SnoopFilter"],
        "enums": [],
        "other_simobjects": ["L2XBar", "SystemXBar", "IOXBar"],
    },
    {
        "mod_name": "Platform",
        "module_path": "src.dev.Platform",
        "dep": "//src/dev:Platform_py",
        "simobjects": ["Platform"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Process",
        "module_path": "src.sim.Process",
        "dep": "//src/sim:Process_py",
        "simobjects": ["Process", "EmulatedDriver"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseInterrupts",
        "module_path": "src.arch.generic.BaseInterrupts",
        "dep": "//src/arch/generic:BaseInterrupts_py",
        "simobjects": ["BaseInterrupts"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Probe",
        "module_path": "src.sim.probe.Probe",
        "dep": "//src/sim/probe:Probe_py",
        "simobjects": ["ProbeListenerObject"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PcCountTracker",
        "module_path": "src.cpu.probes.PcCountTracker",
        "dep": "//src/cpu/probes:PcCountTracker_py",
        "simobjects": ["PcCountTrackerManager", "PcCountTracker"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PortTerminator",
        "module_path": "src.mem.PortTerminator",
        "dep": "//src/mem:PortTerminator_py",
        "simobjects": ["PortTerminator"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Bridge",
        "module_path": "src.mem.Bridge",
        "dep": "//src/mem:Bridge_py",
        "simobjects": ["Bridge", "BridgeBase"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseTrafficGen",
        "module_path": "src.cpu.testers.traffic_gen.BaseTrafficGen",
        "dep": "//src/cpu/testers/traffic_gen:BaseTrafficGen_py",
        "simobjects": ["BaseTrafficGen"],
        "enums": ["StreamGenType"],
        "other_simobjects": [],
    },
    {
        "mod_name": "PyTrafficGen",
        "module_path": "src.cpu.testers.traffic_gen.PyTrafficGen",
        "dep": "//src/cpu/testers/traffic_gen:PyTrafficGen_py",
        "simobjects": ["PyTrafficGen"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SpatterGen",
        "module_path": "src.cpu.testers.spatter_gen.SpatterGen",
        "dep": "//src/cpu/testers/spatter_gen:SpatterGen_py",
        "simobjects": ["SpatterGen"],
        "enums": ["SpatterProcessingMode", "SpatterKernelType"],
        "other_simobjects": [],
    },
    {
        "mod_name": "Prefetcher",
        "module_path": "src.mem.cache.prefetch.Prefetcher",
        "dep": "//src/mem/cache/prefetch:Prefetcher_py",
        "simobjects": [
            "BasePrefetcher",
            "MultiPrefetcher",
            "QueuedPrefetcher",
            "StridePrefetcherHashedSetAssociative",
            "StridePrefetcher",
            "SmsPrefetcher",
            "TaggedPrefetcher",
            "IndirectMemoryPrefetcher",
            "SignaturePathPrefetcher",
            "SignaturePathPrefetcherV2",
            "AccessMapPatternMatching",
            "AMPMPrefetcher",
            "DeltaCorrelatingPredictionTables",
            "DCPTPrefetcher",
            "IrregularStreamBufferPrefetcher",
            "SlimAMPMPrefetcher",
            "BOPPrefetcher",
            "SBOOEPrefetcher",
            "STeMSPrefetcher",
            "PIFPrefetcher",
        ],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ReplacementPolicies",
        "module_path": "src.mem.cache.replacement_policies.ReplacementPolicies",
        "dep": "//src/mem/cache/replacement_policies:ReplacementPolicies_py",
        "simobjects": [
            "BaseReplacementPolicy",
            "DuelingRP",
            "FIFORP",
            "SecondChanceRP",
            "LFURP",
            "LRURP",
            "BIPRP",
            "MRURP",
            "RandomRP",
            "BRRIPRP",
            "SHiPRP",
            "SHiPMemRP",
            "SHiPPCRP",
            "TreePLRURP",
            "WeightedLRURP",
        ],
        "enums": [],
        "other_simobjects": [
            "LIPRP",
            "RRIPRP",
            "DRRIPRP",
            "NRURP",
        ],
    },
    {
        "mod_name": "IndexingPolicies",
        "module_path": "src.mem.cache.tags.indexing_policies.IndexingPolicies",
        "dep": "//src/mem/cache/tags/indexing_policies:IndexingPolicies_py",
        "simobjects": [
            "BaseIndexingPolicy",
            "SetAssociative",
            "SkewedAssociative",
        ],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Tags",
        "module_path": "src.mem.cache.tags.Tags",
        "dep": "//src/mem/cache/tags:Tags_py",
        "simobjects": [
            "TaggedIndexingPolicy",
            "TaggedSetAssociative",
            "BaseTags",
            "BaseSetAssoc",
            "SectorTags",
            "CompressedTags",
            "FALRU",
        ],
        "enums": [],
        "other_simobjects": [
        ],
    },
    {
        "mod_name": "PartitioningPolicies",
        "module_path": "src.mem.cache.tags.partitioning_policies.PartitioningPolicies",
        "dep": "//src/mem/cache/tags/partitioning_policies:PartitioningPolicies_py",
        "simobjects": [
            "PartitionManager",
            "BasePartitioningPolicy",
            "WayPolicyAllocation",
            "WayPartitioningPolicy",
            "MaxCapacityPartitioningPolicy",
        ],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Compressors",
        "module_path": "src.mem.cache.compressors.Compressors",
        "dep": "//src/mem/cache/compressors:Compressors_py",
        "simobjects": [
            "BaseCacheCompressor",
            "BaseDictionaryCompressor",
            "Base64Delta8",
            "Base64Delta16",
            "Base64Delta32",
            "Base32Delta8",
            "Base32Delta16",
            "Base16Delta8",
            "CPack",
            "FPC",
            "FPCD",
            "FrequentValuesCompressor",
            "MultiCompressor",
            "PerfectCompressor",
            "RepeatedQwordsCompressor",
            "ZeroCompressor",
        ],
        "enums": [],
        "other_simobjects": [
            "BDI",
        ],
    },
    {
        "mod_name": "Cache",
        "module_path": "src.mem.cache.Cache",
        "dep": "//src/mem/cache:Cache_py",
        "simobjects": [
            "BaseCache",
            "Cache",
            "NoncoherentCache",
            "WriteAllocator",
        ],
        "enums": [
            "Clusivity",
        ],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseSemihosting",
        "module_path": "src.arch.generic.BaseSemihosting",
        "dep": "//src/arch/generic:BaseSemihosting_py",
        "simobjects": ["BaseSemihosting"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmSemihosting",
        "module_path": "src.arch.arm.ArmSemihosting",
        "dep": "//src/arch/arm:ArmSemihosting_py",
        "simobjects": ["ArmSemihosting"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmSeWorkload",
        "module_path": "src.arch.arm.ArmSeWorkload",
        "dep": "//src/arch/arm:ArmSeWorkload_py",
        "simobjects": ["ArmSEWorkload", "ArmEmuLinux"],  # "ArmEmuFreebsd"
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmNativeTrace",
        "module_path": "src.arch.arm.ArmNativeTrace",
        "dep": "//src/arch/arm:ArmNativeTrace_py",
        "simobjects": ["ArmNativeTrace"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmMMU",
        "module_path": "src.arch.arm.ArmMMU",
        "dep": "//src/arch/arm:ArmMMU_py",
        "simobjects": ["ArmTableWalker", "ArmMMU", "ArmWalkUnit"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmSystem",
        "module_path": "src.arch.arm.ArmSystem",
        "dep": "//src/arch/arm:ArmSystem_py",
        "simobjects": ["ArmRelease", "ArmSystem"],  # "ArmSystem"
        "enums": ["ArmExtension"],
        "other_simobjects": [
            "SveVectorLength",
            "SmeVectorLength",
            "Armv8",
            "ArmDefaultRelease",
            "Armv81",
            "Armv82",
            "Armv83",
            "Armv84",
            "Armv85",
            "Armv86",
            "Armv87",
            "Armv89",
            "Armv90",
            "Armv92",
            "Armv94",
            "ArmAllRelease",
        ],
    },
    {
        "mod_name": "ArmISA",
        "module_path": "src.arch.arm.ArmISA",
        "dep": "//src/arch/arm:ArmISA_py",
        "simobjects": ["ArmISA"],
        "enums": ["DecoderFlavor"],
        "other_simobjects": ["ArmDefaultSERelease"],
    },
    {
        "mod_name": "ArmPMU",
        "module_path": "src.arch.arm.ArmPMU",
        "dep": "//src/arch/arm:ArmPMU_py",
        "simobjects": ["ArmPMU"],
        "enums": ["EventTypeId"],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmDecoder",
        "module_path": "src.arch.arm.ArmDecoder",
        "dep": "//src/arch/arm:ArmDecoder_py",
        "simobjects": ["ArmDecoder"],
        "enums": [],
        "other_simobjects": [],
    },
    # TODO(Add the simobjects and enums correctly everything but Gic400 should be in simobjects)
    {
        "mod_name": "Gic",
        "module_path": "src.dev.arm.Gic",
        "dep": "//src/dev/arm:Gic_py",
        "simobjects": ["BaseGic", "ArmInterruptPin", "ArmSPI", "ArmPPI", "ArmSigInterruptPin", "GicV2", "Gicv2m", "Gicv2mFrame", "VGic", "Gicv3Its", "Gicv3"],
        "enums": ["ArmInterruptType"],
        "other_simobjects": ["Gic400"],
    },
    {
        "mod_name": "ArmTLB",
        "module_path": "src.arch.arm.ArmTLB",
        "dep": "//src/arch/arm:ArmTLB_py",
        "simobjects": ["TLBIndexingPolicy", "TLBSetAssociative", "ArmTLB"],
        "enums": ["ArmLookupLevel"],
        "other_simobjects": ["ArmStage2TLB"],
    },
    {
        "mod_name": "ArmFsWorkload",
        "module_path": "src.arch.arm.ArmFsWorkload",
        "dep": "//src/arch/arm:ArmFsWorkload_py",
        "simobjects": ["ArmFsWorkload", "ArmFsLinux"],  # "ArmFsFreebsd"]
        "enums": ["ArmMachineType"],
        "other_simobjects": [],
    },
    {
        "mod_name": "Serial",
        "module_path": "src.dev.serial.Serial",
        "dep": "//src/dev/serial:Serial_py",
        "simobjects": ["SerialDevice", "SerialNullDevice"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "RealView",
        "module_path": "src.dev.arm.RealView",
        "dep": "//src/dev/arm:RealView_py",
        "simobjects": [
            "AmbaPioDevice",
            "AmbaIntDevice",
            "AmbaDmaDevice",
            "A9SCU",
            "GenericArmPciHost",
            "RealViewCtrl",
            "RealViewOsc",
            "RealViewTemperatureSensor",
            "SysSecCtrl",
            "AmbaFake",
            "Pl011",
            "Sp804",
            "Sp805",
            "GenericWatchdog",
            "CpuLocalTimer",
            "PL031",
            "Pl050",
            "Pl111",
            "HDLcd",
            "FVPBasePwrCtrl",
            "RealView",
        ],
        "enums": ["ArmPciIntRouting"],
        "other_simobjects": [
            "VExpressMCC",
            "CoreTile2A15DCC",
            "FixedClock",
            "ParentMem",
            "MmioSRAM",
            "GenericMHU",
            "VExpress_EMM",
            "VExpress_EMM64",
            "VExpress_GEM5_Base",
            "VExpress_GEM5_V1_Base",
            "VExpress_GEM5_V1",
            "VExpress_GEM5_V1_HDLcd",
            "VExpress_GEM5_V2_Base",
            "VExpress_GEM5_V2",
            "VExpress_GEM5_V2_HDLcd",
            "VExpress_GEM5_Foundation",
        ],
    },
    {
        "mod_name": "BranchPredictor",
        "module_path": "src.cpu.pred.BranchPredictor",
        "dep": "//src/cpu/pred:BranchPredictor_py",
        "simobjects": [
            "ReturnAddrStack",
            "BranchTargetBuffer",
            "BTBIndexingPolicy",
            "BTBSetAssociative",
            "SimpleBTB",
            "ConditionalPredictor",
            "IndirectPredictor",
            "SimpleIndirectPredictor",
            "BranchPredictor",
            "LocalBP",
            "TournamentBP",
            "BiModeBP",
            "TAGEBase",
            "TAGE",
            "LoopPredictor",
            "TAGE_SC_L_TAGE",
            "TAGE_SC_L_TAGE_64KB",
            "TAGE_SC_L_TAGE_8KB",
            "LTAGE",
            "TAGE_SC_L_LoopPredictor",
            "StatisticalCorrector",
            "TAGE_SC_L",
            "TAGE_SC_L_64KB_StatisticalCorrector",
            "TAGE_SC_L_8KB_StatisticalCorrector",
            "TAGE_SC_L_64KB",
            "TAGE_SC_L_8KB",
            "MultiperspectivePerceptron",
            "MultiperspectivePerceptron8KB",
            "MultiperspectivePerceptron64KB",
            "MPP_TAGE",
            "MPP_LoopPredictor",
            "MPP_StatisticalCorrector",
            "MultiperspectivePerceptronTAGE",
            "MPP_StatisticalCorrector_64KB",
            "MultiperspectivePerceptronTAGE64KB",
            "MPP_TAGE_8KB",
            "MPP_LoopPredictor_8KB",
            "MPP_StatisticalCorrector_8KB",
            "MultiperspectivePerceptronTAGE8KB",
            "GshareBP",
            "ITTAGE_TAGE",
            "ITTAGE",
        ],
        "enums": ["BranchType", "TargetProvider"],
        "other_simobjects": [
            "LTAGE_TAGE",
            "TAGE_SC_L_64KB_LoopPredictor",
            "TAGE_SC_L_8KB_LoopPredictor",
        ],
    },
    {
        "mod_name": "BaseSimpleCPU",
        "module_path": "src.cpu.simple.BaseSimpleCPU",
        "dep": "//src/cpu/simple:BaseSimpleCPU_py",
        "simobjects": ["BaseSimpleCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseAtomicSimpleCPU",
        "module_path": "src.cpu.simple.BaseAtomicSimpleCPU",
        "dep": "//src/cpu/simple:BaseAtomicSimpleCPU_py",
        "simobjects": ["BaseAtomicSimpleCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SimPoint",
        "module_path": "src.cpu.simple.probes.SimPoint",
        "dep": "//src/cpu/simple/probes:SimPoint_py",
        "simobjects": ["SimPoint"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseTimingSimpleCPU",
        "module_path": "src.cpu.simple.BaseTimingSimpleCPU",
        "dep": "//src/cpu/simple:BaseTimingSimpleCPU_py",
        "simobjects": ["BaseTimingSimpleCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseNonCachingSimpleCPU",
        "module_path": "src.cpu.simple.BaseNonCachingSimpleCPU",
        "dep": "//src/cpu/simple:BaseNonCachingSimpleCPU_py",
        "simobjects": ["BaseNonCachingSimpleCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseO3Checker",
        "module_path": "src.cpu.o3.BaseO3Checker",
        "dep": "//src/cpu/o3:BaseO3Checker_py",
        "simobjects": ["BaseO3Checker"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseO3CPU",
        "module_path": "src.cpu.o3.BaseO3CPU",
        "dep": "//src/cpu/o3:BaseO3CPU_py",
        "simobjects": ["BaseO3CPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmInterrupts",
        "module_path": "src.arch.arm.ArmInterrupts",
        "dep": "//src/arch/arm:ArmInterrupts_py",
        "simobjects": ["ArmInterrupts"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "StaticInstFlags",
        "module_path": "src.cpu.StaticInstFlags",
        "dep": "//src/cpu:StaticInstFlags_py",
        "simobjects": [],
        "enums": ["StaticInstFlags"],
        "other_simobjects": [],
    },
    {
        "mod_name": "ArmCPU",
        "module_path": "src.arch.arm.ArmCPU",
        "dep": "//src/arch/arm:ArmCPU_py",
        "simobjects": [],
        "enums": [],
        "other_simobjects": ["ArmCPU", "ArmAtomicSimpleCPU", "ArmNonCachingSimpleCPU", "ArmTimingSimpleCPU", "ArmO3Checker", "ArmO3CPU", "ArmMinorCPU"],
    },
    {
        "mod_name": "RubySystem",
        "module_path": "src.mem.ruby.system.RubySystem",
        "dep": "//src/mem/ruby/system:RubySystem_py",
        "simobjects": ["RubySystem"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Controller",
        "module_path": "src.mem.ruby.slicc_interface.Controller",
        "dep": "//src/mem/ruby/slicc_interface:Controller_py",
        "simobjects": ["RubyController"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MessageBuffer",
        "module_path": "src.mem.ruby.network.MessageBuffer",
        "dep": "//src/mem/ruby/network:MessageBuffer_py",
        "simobjects": ["MessageBuffer"],
        "enums": ["MessageRandomization"],
        "other_simobjects": [],
    },
    {
        "mod_name": "Network",
        "module_path": "src.mem.ruby.network.Network",
        "dep": "//src/mem/ruby/network:Network_py",
        "simobjects": ["RubyNetwork"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BasicLink",
        "module_path": "src.mem.ruby.network.BasicLink",
        "dep": "//src/mem/ruby/network:BasicLink_py",
        "simobjects": ["BasicLink", "BasicExtLink", "BasicIntLink"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BasicRouter",
        "module_path": "src.mem.ruby.network.BasicRouter",
        "dep": "//src/mem/ruby/network:BasicRouter_py",
        "simobjects": ["BasicRouter"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "DirectoryMemory",
        "module_path": "src.mem.ruby.structures.DirectoryMemory",
        "dep": "//src/mem/ruby/structures:DirectoryMemory_py",
        "simobjects": ["RubyDirectoryMemory"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "RubyCache",
        "module_path": "src.mem.ruby.structures.RubyCache",
        "dep": "//src/mem/ruby/structures:RubyCache_py",
        "simobjects": ["RubyCache"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Sequencer",
        "module_path": "src.mem.ruby.system.Sequencer",
        "dep": "//src/mem/ruby/system:Sequencer_py",
        "simobjects": ["RubyPort", "RubySequencer", "RubyHTMSequencer", "DMASequencer", "RubyPortProxy"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "RubyPrefetcher",
        "module_path": "src.mem.ruby.structures.RubyPrefetcher",
        "dep": "//src/mem/ruby/structures:RubyPrefetcher_py",
        "simobjects": ["RubyPrefetcher"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "WireBuffer",
        "module_path": "src.mem.ruby.structures.WireBuffer",
        "dep": "//src/mem/ruby/structures:WireBuffer_py",
        "simobjects": ["RubyWireBuffer"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MESI_Two_Level_L1Cache_Controller",
        "module_path": "src.mem.ruby.protocol.MESI_Two_Level_L1Cache_Controller",
        "dep": "//src/mem/ruby/protocol:MESI_Two_Level_L1Cache_Controller_py",
        "simobjects": ["MESI_Two_Level_L1Cache_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MESI_Two_Level_L2Cache_Controller",
        "module_path": "src.mem.ruby.protocol.MESI_Two_Level_L2Cache_Controller",
        "dep": "//src/mem/ruby/protocol:MESI_Two_Level_L2Cache_Controller_py",
        "simobjects": ["MESI_Two_Level_L2Cache_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MESI_Two_Level_DMA_Controller",
        "module_path": "src.mem.ruby.protocol.MESI_Two_Level_DMA_Controller",
        "dep": "//src/mem/ruby/protocol:MESI_Two_Level_DMA_Controller_py",
        "simobjects": ["MESI_Two_Level_DMA_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MESI_Two_Level_Directory_Controller",
        "module_path": "src.mem.ruby.protocol.MESI_Two_Level_Directory_Controller",
        "dep": "//src/mem/ruby/protocol:MESI_Two_Level_Directory_Controller_py",
        "simobjects": ["MESI_Two_Level_Directory_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SimpleNetwork",
        "module_path": "src.mem.ruby.network.simple.SimpleNetwork",
        "dep": "//src/mem/ruby/network/simple:SimpleNetwork_py",
        "simobjects": ["SimpleNetwork", "BaseRoutingUnit", "WeightBased", "Switch"],
        "enums": [],
        "other_simobjects": ["SwitchPortBuffer"],
    },
    {
        "mod_name": "SimpleLink",
        "module_path": "src.mem.ruby.network.simple.SimpleLink",
        "dep": "//src/mem/ruby/network/simple:SimpleLink_py",
        "simobjects": ["SimpleExtLink", "SimpleIntLink"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CHI_Cache_Controller",
        "module_path": "src.mem.ruby.protocol.CHI_Cache_Controller",
        "dep": "//src/mem/ruby/protocol:CHI_Cache_Controller_py",
        "simobjects": ["CHI_Cache_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CHI_Memory_Controller",
        "module_path": "src.mem.ruby.protocol.CHI_Memory_Controller",
        "dep": "//src/mem/ruby/protocol:CHI_Memory_Controller_py",
        "simobjects": ["CHI_Memory_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CHI_MiscNode_Controller",
        "module_path": "src.mem.ruby.protocol.CHI_MiscNode_Controller",
        "dep": "//src/mem/ruby/protocol:CHI_MiscNode_Controller_py",
        "simobjects": ["CHI_MiscNode_Controller"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CHIGeneric",
        "module_path": "src.mem.ruby.protocol.CHI.generic.CHIGeneric",
        "dep": "//src/mem/ruby/protocol/CHI/generic:CHIGeneric_py",
        "simobjects": ["CHIGenericController"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "QoSMemCtrl",
        "module_path": "src.mem.qos.QoSMemCtrl",
        "dep": "//src/mem/qos:QoSMemCtrl_py",
        "simobjects": ["QoSMemCtrl"],
        "enums": ["QoSQPolicy"],
        "other_simobjects": [],
    },
    {
        "mod_name": "QoSMemSinkCtrl",
        "module_path": "src.mem.qos.QoSMemSinkCtrl",
        "dep": "//src/mem/qos:QoSMemSinkCtrl_py",
        "simobjects": ["QoSMemSinkCtrl"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "QoSMemSinkInterface",
        "module_path": "src.mem.qos.QoSMemSinkInterface",
        "dep": "//src/mem/qos:QoSMemSinkInterface_py",
        "simobjects": ["QoSMemSinkInterface"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "QoSPolicy",
        "module_path": "src.mem.qos.QoSPolicy",
        "dep": "//src/mem/qos:QoSPolicy_py",
        "simobjects": ["QoSPolicy", "QoSFixedPriorityPolicy", "QoSPropFairPolicy"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MemCtrl",
        "module_path": "src.mem.MemCtrl",
        "dep": "//src/mem:MemCtrl_py",
        "simobjects": ["MemCtrl"],
        "enums": ["MemSched"],
        "other_simobjects": [],
    },
    {
        "mod_name": "HBMCtrl",
        "module_path": "src.mem.HBMCtrl",
        "dep": "//src/mem:HBMCtrl_py",
        "simobjects": ["HBMCtrl"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MemInterface",
        "module_path": "src.mem.MemInterface",
        "dep": "//src/mem:MemInterface_py",
        "simobjects": ["MemInterface"],
        "enums": ["AddrMap"],
        "other_simobjects": [],
    },
    {
        "mod_name": "QoSTurnaround",
        "module_path": "src.mem.qos.QoSTurnaround",
        "dep": "//src/mem/qos:QoSTurnaround_py",
        "simobjects": ["QoSTurnaroundPolicy", "QoSTurnaroundPolicyIdeal"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "DRAMInterface",
        "module_path": "src.mem.DRAMInterface",
        "dep": "//src/mem:DRAMInterface_py",
        "simobjects": ["DRAMInterface"],
        "enums": ["PageManage"],
        "other_simobjects": [],
    },
    {
        "mod_name": "CfiMemory",
        "module_path": "src.mem.CfiMemory",
        "dep": "//src/mem:CfiMemory_py",
        "simobjects": ["CfiMemory"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "CommMonitor",
        "module_path": "src.mem.CommMonitor",
        "dep": "//src/mem:CommMonitor_py",
        "simobjects": ["CommMonitor"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "AddrMapper",
        "module_path": "src.mem.AddrMapper",
        "dep": "//src/mem:AddrMapper_py",
        "simobjects": ["AddrMapper", "RangeAddrMapper"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "FuncUnitConfig",
        "module_path": "src.cpu.o3.FuncUnitConfig",
        "dep": "//src/cpu/o3:FuncUnitConfig_py",
        "simobjects": [
        ],
        "enums": [],
        "other_simobjects": [
            "IntALU",
            "IntMultDiv",
            "FP_ALU",
            "FP_MultDiv",
            "SIMD_Unit",
            "Matrix_Unit",
            "System_Unit",
            "PredALU",
            "ReadPort",
            "WritePort",
            "RdWrPort",
        ],
    },
    {
        "mod_name": "FuncUnit",
        "module_path": "src.cpu.FuncUnit",
        "dep": "//src/cpu:FuncUnit_py",
        "simobjects": ["FUDesc", "OpDesc"],
        "enums": ["OpClass"],
        "other_simobjects": [],
    },
    {
        "mod_name": "FUPool",
        "module_path": "src.cpu.o3.FUPool",
        "dep": "//src/cpu/o3:FUPool_py",
        "simobjects": ["FUPool"],
        "enums": [],
        "other_simobjects": ["DefaultFUPool"],
    },
    {
        "mod_name": "IQUnit",
        "module_path": "src.cpu.o3.IQUnit",
        "dep": "//src/cpu/o3:IQUnit_py",
        "simobjects": ["IQUnit"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SMT",
        "module_path": "src.cpu.o3.SMT",
        "dep": "//src/cpu/o3:SMT_py",
        "simobjects": [],
        "enums": ["SMTFetchPolicy", "SMTQueuePolicy", "CommitPolicy"],
        "other_simobjects": [],
    },
    {
        "mod_name": "EnergyCtrl",
        "module_path": "src.dev.arm.EnergyCtrl",
        "dep": "//src/dev/arm:EnergyCtrl_py",
        "simobjects": ["EnergyCtrl"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Uart",
        "module_path": "src.dev.serial.Uart",
        "dep": "//src/dev/serial:Uart_py",
        "simobjects": ["Uart", "SimpleUart", "Uart8250"],
        "enums": [],
        "other_simobjects": ["RiscvUart8250"],
    },
    {
        "mod_name": "Terminal",
        "module_path": "src.dev.serial.Terminal",
        "dep": "//src/dev/serial:Terminal_py",
        "simobjects": ["Terminal"],
        "enums": ["TerminalDump"],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIOMMIO",
        "module_path": "src.dev.arm.VirtIOMMIO",
        "dep": "//src/dev/arm:VirtIOMMIO_py",
        "simobjects": ["MmioVirtIO"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Scp",
        "module_path": "src.dev.arm.css.Scp",
        "dep": "//src/dev/arm/css:Scp_py",
        "simobjects": ["Scp"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "MHU",
        "module_path": "src.dev.arm.css.MHU",
        "dep": "//src/dev/arm/css:MHU_py",
        "simobjects": ["MHU", "MhuDoorbell", "Ap2ScpDoorbell", "Scp2ApDoorbell"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Scmi",
        "module_path": "src.dev.arm.css.Scmi",
        "dep": "//src/dev/arm/css:Scmi_py",
        "simobjects": ["ScmiPlatform", "ScmiCommunication", "ScmiChannel", "ScmiAgentChannel", "ScmiPlatformChannel"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Doorbell",
        "module_path": "src.dev.arm.Doorbell",
        "dep": "//src/dev/arm:Doorbell_py",
        "simobjects": ["Doorbell"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PciHost",
        "module_path": "src.dev.pci.PciHost",
        "dep": "//src/dev/pci:PciHost_py",
        "simobjects": ["GenericPciHost", "PciHost"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PciDevice",
        "module_path": "src.dev.pci.PciDevice",
        "dep": "//src/dev/pci:PciDevice_py",
        "simobjects": [
            "PciDevice",
            "PciEndpoint",
            "PciType1Device",
            "PciBar",
            "PciBarNone",
            "PciIoBar",
            "PciLegacyIoBar",
            "PciMemBar",
            "PciMemUpperBar",
        ],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PciUpstream",
        "module_path": "src.dev.pci.PciUpstream",
        "dep": "//src/dev/pci:PciUpstream_py",
        "simobjects": ["PciBus", "PciUpstream", "PciConfigError", "PciUpDownBridge"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIO",
        "module_path": "src.dev.virtio.VirtIO",
        "dep": "//src/dev/virtio:VirtIO_py",
        "simobjects": ["VirtIODeviceBase", "VirtIODummyDevice", "PciVirtIO"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "SMMUv3",
        "module_path": "src.dev.arm.SMMUv3",
        "dep": "//src/dev/arm:SMMUv3_py",
        "simobjects": ["SMMUv3", "SMMUv3DeviceInterface"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "KvmGic",
        "module_path": "src.arch.arm.kvm.KvmGic",
        "dep": "//src/arch/arm/kvm:KvmGic_py",
        "simobjects": ["MuxingKvmGicV2", "MuxingKvmGicV3"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "PS2",
        "module_path": "src.dev.ps2.PS2",
        "dep": "//src/dev/ps2:PS2_py",
        "simobjects": ["PS2Device", "PS2Keyboard", "PS2Mouse", "PS2TouchKit"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "GenericTimer",
        "module_path": "src.dev.arm.GenericTimer",
        "dep": "//src/dev/arm:GenericTimer_py",
        "simobjects": ["GenericTimer", "SystemCounter", "GenericTimerFrame", "GenericTimerMem"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Ethernet",
        "module_path": "src.dev.net.Ethernet",
        "dep": "//src/dev/net:Ethernet_py",
        "simobjects": [
            "EtherLink",
            "DistEtherLink",
            "EtherBus",
            "EtherSwitch",
            "EtherTapBase",
            "EtherTapStub",
            "EtherDump",
            "EtherDevice",
            "IGbE",
            "EtherDevBase",
            "NSGigE",
            "Sinic",
        ],
        "enums": [],
        "other_simobjects": ["IGbE_e1000", "IGbE_igb"],
    },
    {
        "mod_name": "Graphics",
        "module_path": "src.base.Graphics",
        "dep": "//src/base:Graphics_py",
        "simobjects": [],
        "enums": ["ImageFormat"],
        "other_simobjects": [],
    },
    {
        "mod_name": "Vnc",
        "module_path": "src.base.vnc.Vnc",
        "dep": "//src/base/vnc:Vnc_py",
        "simobjects": ["VncServer"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VncInput",
        "module_path": "src.base.vnc.Vnc",
        "dep": "//src/base/vnc:Vnc_py",
        "simobjects": ["VncInput"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "Ide",
        "module_path": "src.dev.storage.Ide",
        "dep": "//src/dev/storage:Ide_py",
        "simobjects": ["IdeController", "IdeDisk"],
        "enums": ["IdeID"],
        "other_simobjects": [],
    },
    {
        "mod_name": "DiskImage",
        "module_path": "src.dev.storage.DiskImage",
        "dep": "//src/dev/storage:DiskImage_py",
        "simobjects": ["DiskImage", "RawDiskImage", "CowDiskImage"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseKvmCPU",
        "module_path": "src.cpu.kvm.BaseKvmCPU",
        "dep": "//src/cpu/kvm:BaseKvmCPU_py",
        "simobjects": ["BaseKvmCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "KvmVM",
        "module_path": "src.cpu.kvm.KvmVM",
        "dep": "//src/cpu/kvm:KvmVM_py",
        "simobjects": ["KvmVM"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "BaseArmKvmCPU",
        "module_path": "src.arch.arm.kvm.BaseArmKvmCPU",
        "dep": "//src/arch/arm/kvm:BaseArmKvmCPU_py",
        "simobjects": ["BaseArmKvmCPU"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIOBlock",
        "module_path": "src.dev.virtio.VirtIOBlock",
        "dep": "//src/dev/virtio:virt_io_block",
        "simobjects": ["VirtIOBlock"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIOConsole",
        "module_path": "src.dev.virtio.VirtIOConsole",
        "dep": "//src/dev/virtio:virt_io_console",
        "simobjects": ["VirtIOConsole"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIORng",
        "module_path": "src.dev.virtio.VirtIORng",
        "dep": "//src/dev/virtio:virt_io_rng",
        "simobjects": ["VirtIORng"],
        "enums": [],
        "other_simobjects": [],
    },
    {
        "mod_name": "VirtIO9P",
        "module_path": "src.dev.virtio.VirtIO9P",
        "dep": "//src/dev/virtio:virt_io9p",
        "simobjects": ["VirtIO9PBase", "VirtIO9PProxy", "VirtIO9PDiod", "VirtIO9PSocket"],
        "enums": [],
        "other_simobjects": [],
    },
]
