load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "softfloat",
    srcs = glob(
        ["*.c"],
        exclude = [
            "*_test.c",
            # Exclude non-FAST_INT64 multi-word variants (extF80M_*, f128M_*,
            # and their internal helpers). We use SOFTFLOAT_FAST_INT64 mode.
            "extF80M_*.c",
            "f128M_*.c",
            "s_addExtF80M.c",
            "s_addF128M.c",
            "s_addM.c",
            "s_addCarryM.c",
            "s_addComplCarryM.c",
            "s_compareNonnormExtF80M.c",
            "s_compare128M.c",
            "s_compare96M.c",
            "s_invalidExtF80M.c",
            "s_invalidF128M.c",
            "s_isNaNF128M.c",
            "s_mulAddF128M.c",
            "s_mul128MTo256M.c",
            "s_mul64To128M.c",
            "s_negXM.c",
            "s_normExtF80SigM.c",
            "s_normRoundPackMToExtF80M.c",
            "s_normRoundPackMToF128M.c",
            "s_normSubnormalF128SigM.c",
            "s_remStepMBy32.c",
            "s_roundMToI64.c",
            "s_roundMToUI64.c",
            "s_roundPackMToExtF80M.c",
            "s_roundPackMToF128M.c",
            "s_roundPackMToI64.c",
            "s_roundPackMToUI64.c",
            "s_shiftLeftM.c",
            "s_shiftNormSigF128M.c",
            "s_shiftRightJamM.c",
            "s_shiftRightM.c",
            "s_shortShiftLeftM.c",
            "s_shortShiftLeft64To96M.c",
            "s_shortShiftRightJamM.c",
            "s_shortShiftRightM.c",
            "s_subM.c",
            "s_sub1XM.c",
            "s_tryPropagateNaNExtF80M.c",
            "s_tryPropagateNaNF128M.c",
        ],
    ),
    hdrs = glob(["*.h"]),
    includes = ["."],
    copts = [
        "-Wno-implicit-fallthrough",
        "-Wno-unused-variable",
        "-Wno-implicit-function-declaration",
    ],
    local_defines = ["SOFTFLOAT_FAST_INT64"],
    visibility = ["//visibility:public"],
)
