"""Rule for SLICC protocol compilation.

Compiles .slicc protocol definitions into C++ controller code and
SimObject Python files. Uses manifest-declared outputs when available
(generated by configure.bzl), falling back to tree artifacts when
manifests are empty or unavailable.

SLICC-generated code includes external types as "mem/ruby/protocol/<Type>.hh"
but the actual headers live in subdirectories (common/, structures/, etc.).
Forwarding headers are generated alongside SLICC output to redirect these
includes, matching CMake's _ruby_make_include() mechanism.

SLICC also generates controller SimObject .py files that must be fed
into the SimObject aggregate param generator. These are exposed via the
SliccInfo provider and extracted by _slicc_py_extract for downstream use.
"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//configs:slicc_manifests.bzl", "SLICC_MANIFESTS", "SLICC_PY_MANIFESTS")

# Provider to carry SLICC-generated .py files separately from .cc/.hh.
SliccInfo = provider(
    doc = "SLICC compilation outputs split by type.",
    fields = {
        "py_files": "depset of generated SimObject .py files",
    },
)

# Forwarding headers for external types referenced by SLICC-generated code.
# Maps basename -> actual include path relative to mem/ruby/.
# Matches CMake's _ruby_make_include() calls in protocol/CMakeLists.txt.
_SLICC_FORWARDING_HEADERS = {
    "AbstractCacheEntry.hh": "slicc_interface/AbstractCacheEntry.hh",
    "Message.hh": "slicc_interface/Message.hh",
    "RubyRequest.hh": "slicc_interface/RubyRequest.hh",
    "Address.hh": "common/Address.hh",
    "BoolVec.hh": "common/BoolVec.hh",
    "DataBlock.hh": "common/DataBlock.hh",
    "ExpectedMap.hh": "common/ExpectedMap.hh",
    "IntVec.hh": "common/IntVec.hh",
    "MachineID.hh": "common/MachineID.hh",
    "NetDest.hh": "common/NetDest.hh",
    "TriggerQueue.hh": "common/TriggerQueue.hh",
    "Set.hh": "common/Set.hh",
    "WriteMask.hh": "common/WriteMask.hh",
    "MessageBuffer.hh": "network/MessageBuffer.hh",
    "CacheMemory.hh": "structures/CacheMemory.hh",
    "DirectoryMemory.hh": "structures/DirectoryMemory.hh",
    "PerfectCacheMemory.hh": "structures/PerfectCacheMemory.hh",
    "PersistentTable.hh": "structures/PersistentTable.hh",
    "RubyPrefetcher.hh": "structures/RubyPrefetcher.hh",
    "RubyPrefetcherProxy.hh": "structures/RubyPrefetcherProxy.hh",
    "TBEStorage.hh": "structures/TBEStorage.hh",
    "TBETable.hh": "structures/TBETable.hh",
    "TimerTable.hh": "structures/TimerTable.hh",
    "WireBuffer.hh": "structures/WireBuffer.hh",
    "DMASequencer.hh": "system/DMASequencer.hh",
    "Sequencer.hh": "system/Sequencer.hh",
    "GPUCoalescer.hh": "system/GPUCoalescer.hh",
    "HTMSequencer.hh": "system/HTMSequencer.hh",
    "VIPERCoalescer.hh": "system/VIPERCoalescer.hh",
    "VIPERSequencer.hh": "system/VIPERSequencer.hh",
    "MN_TBEStorage.hh": "structures/MN_TBEStorage.hh",
    "MN_TBETable.hh": "structures/MN_TBETable.hh",
}

def _forwarding_header_cmds(output_dir):
    """Generate shell commands to create forwarding headers in output_dir."""
    cmds = []
    for basename, subpath in _SLICC_FORWARDING_HEADERS.items():
        cmds.append(
            "printf '\\x23include \"mem/ruby/{subpath}\"\\n' > {dir}/{basename}".format(
                subpath = subpath,
                dir = output_dir,
                basename = basename,
            ),
        )
    return " && ".join(cmds)

def _slicc_gen_impl(ctx):
    """Run SLICC to generate C++ and Python from protocol definitions."""
    src = ctx.file.src
    protocol = ctx.attr.protocol
    cc_manifest = SLICC_MANIFESTS.get(protocol, [])
    py_manifest = SLICC_PY_MANIFESTS.get(protocol, [])

    # Find SLICC init for path setup
    slicc_init = None
    for f in ctx.files._slicc_files:
        if f.path.endswith("slicc/__init__.py"):
            slicc_init = f
            break

    ply_init = None
    for f in ctx.files._ply_files:
        if f.path.endswith("ply/__init__.py"):
            ply_init = f
            break

    grammar_file = None
    for f in ctx.files._grammar_files:
        if f.path.endswith("grammar.py"):
            grammar_file = f
            break

    script = ctx.actions.declare_file("_run_slicc_{}.py".format(ctx.label.name))
    ctx.actions.write(
        output = script,
        content = """\
import sys
import os

slicc_file = sys.argv[1]
code_output_dir = sys.argv[2]
slicc_init = sys.argv[3]
ply_init = sys.argv[4]
grammar_file = sys.argv[5]

# Set up import paths
slicc_parent = os.path.dirname(os.path.dirname(slicc_init))
sys.path.insert(0, slicc_parent)

ply_parent = os.path.dirname(os.path.dirname(ply_init))
sys.path.insert(0, ply_parent)

grammar_dir = os.path.dirname(grammar_file)
sys.path.insert(0, grammar_dir)

from slicc.parser import SLICC

os.makedirs(code_output_dir, exist_ok=True)

protocol_base = os.path.dirname(slicc_file)

# Find interfaces slicc file (may be in protocol_base or parent for
# subdirectory protocols like CHI)
interfaces_slicc = os.path.join(protocol_base, "RubySlicc_interfaces.slicc")
if not os.path.exists(interfaces_slicc):
    interfaces_slicc = os.path.join(os.path.dirname(protocol_base), "RubySlicc_interfaces.slicc")
interfaces_list = [interfaces_slicc] if os.path.exists(interfaces_slicc) else []

slicc = SLICC(slicc_file, interfaces_list, protocol_base)
slicc.process()
slicc.writeCodeFiles(code_output_dir, ["mem/ruby/slicc_interface/RubySlicc_includes.hh"])
""",
    )

    all_inputs = [src, script] + ctx.files.sm_sources + \
                 ctx.files._slicc_files + ctx.files._ply_files + \
                 ctx.files._grammar_files

    if cc_manifest:
        # Manifest-based: declare individual output files.
        # Files go under mem/ruby/protocol/ within the slicc_ prefix
        # so #include "mem/ruby/protocol/X.hh" resolves correctly.
        prefix = "slicc_{}/mem/ruby/protocol".format(protocol)
        cc_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in cc_manifest]

        # Also declare forwarding headers for external types.
        fwd_outputs = [
            ctx.actions.declare_file("{}/{}".format(prefix, basename))
            for basename in _SLICC_FORWARDING_HEADERS.keys()
        ]

        # Declare .py outputs for SimObject controller definitions.
        py_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in py_manifest]

        all_outputs = cc_outputs + fwd_outputs + py_outputs
        # Use forwarding header dirname for the protocol root directory.
        # Manifest entries may have protocol subdirectories (MESI_Two_Level/...)
        # but forwarding headers always go at the protocol root level.
        proto_root_dir = fwd_outputs[0].dirname

        ctx.actions.run_shell(
            outputs = all_outputs,
            inputs = all_inputs,
            command = "{fwd_cmds} && python3 {script} {src} {outdir} {slicc} {ply} {grammar}".format(
                fwd_cmds = _forwarding_header_cmds(proto_root_dir),
                script = script.path,
                src = src.path,
                outdir = proto_root_dir,
                slicc = slicc_init.path if slicc_init else "",
                ply = ply_init.path if ply_init else "",
                grammar = grammar_file.path if grammar_file else "",
            ),
            mnemonic = "SLICC",
            progress_message = "Compiling SLICC protocol {} (manifest)".format(protocol),
        )

        return [
            DefaultInfo(files = depset(cc_outputs + fwd_outputs)),
            SliccInfo(py_files = depset(py_outputs)),
        ]
    else:
        # Fallback: tree artifact for dynamic output.
        # SLICC writes into mem/ruby/protocol/ subdirectory within the
        # tree artifact so #include "mem/ruby/protocol/X.hh" resolves.
        out_dir = ctx.actions.declare_directory("slicc_{}".format(protocol))
        nested_path = "{}/mem/ruby/protocol".format(out_dir.path)

        ctx.actions.run_shell(
            outputs = [out_dir],
            inputs = all_inputs,
            command = "mkdir -p {nested} && {fwd_cmds} && python3 {script} {src} {nested} {slicc} {ply} {grammar}".format(
                nested = nested_path,
                fwd_cmds = _forwarding_header_cmds("{nested}".format(nested = nested_path)),
                script = script.path,
                src = src.path,
                slicc = slicc_init.path if slicc_init else "",
                ply = ply_init.path if ply_init else "",
                grammar = grammar_file.path if grammar_file else "",
            ),
            mnemonic = "SLICC",
            progress_message = "Compiling SLICC protocol {} (tree)".format(protocol),
        )

        return [
            DefaultInfo(files = depset([out_dir])),
            SliccInfo(py_files = depset()),
        ]

_slicc_gen = rule(
    implementation = _slicc_gen_impl,
    attrs = {
        "src": attr.label(mandatory = True, allow_single_file = [".slicc"]),
        "protocol": attr.string(mandatory = True),
        "sm_sources": attr.label_list(
            allow_files = [".sm", ".slicc"],
            doc = "State machine and protocol files.",
        ),
        "_slicc_files": attr.label(
            default = "//src/mem/slicc:slicc_files",
            allow_files = True,
        ),
        "_ply_files": attr.label(
            default = "@gem5_ext_ply//:ply_files",
            allow_files = True,
        ),
        "_grammar_files": attr.label(
            default = "//build_tools:grammar_files",
            allow_files = True,
        ),
    },
)

def _slicc_py_extract_impl(ctx):
    """Extract SLICC-generated .py files from SliccInfo provider."""
    slicc_info = ctx.attr.slicc_gen[SliccInfo]
    return [DefaultInfo(files = slicc_info.py_files)]

_slicc_py_extract = rule(
    implementation = _slicc_py_extract_impl,
    attrs = {
        "slicc_gen": attr.label(
            mandatory = True,
            providers = [SliccInfo],
        ),
    },
)

def gem5_slicc_protocol(name, src, protocol = None, sm_sources = [],
                        visibility = None, deps = [], copts = []):
    """Compile a SLICC protocol into C++ sources and SimObject .py files.

    Uses manifest-declared outputs when available (from configs/slicc_manifests.bzl),
    falling back to tree artifacts for protocols with empty or missing manifests.

    Creates two targets:
      {name}:     cc_library with compiled SLICC C++ code.
      {name}_py:  Filegroup of generated SimObject .py files.

    Args:
        name: Target name (typically the protocol name).
        src: The main .slicc file.
        protocol: Protocol name. Defaults to name.
        sm_sources: State machine .sm files and included .slicc files.
        visibility: Visibility.
        deps: Dependencies for the generated cc_library.
        copts: Additional compiler flags.
    """
    if protocol == None:
        protocol = name

    gen_name = "_gen_slicc_{}".format(name)

    _slicc_gen(
        name = gen_name,
        src = src,
        protocol = protocol,
        sm_sources = sm_sources,
    )

    cc_library(
        name = name,
        srcs = [":{}".format(gen_name)],
        hdrs = [":{}".format(gen_name)],
        deps = deps + ["//src:gem5_hdrs"],
        copts = copts + ["-Wno-unused-variable", "-DNUMBER_BITS_PER_SET=64"],
        # Include SLICC output root so #include "mem/ruby/protocol/X.hh"
        # resolves for both generated .cc and downstream consumers.
        includes = [".", "slicc_{}".format(name)],
        visibility = visibility,
        alwayslink = True,
    )

    _slicc_py_extract(
        name = name + "_py",
        slicc_gen = ":{}".format(gen_name),
        visibility = visibility,
    )
