# -*- mode:python -*-

# Copyright (c) 2004-2005 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Authors: Gabe Black
#          Steve Reinhardt

Import('*')

if env['TARGET_ISA'] == 'sparc':
    Source('asi.cc')
    Source('decoder.cc')
    Source('faults.cc')
    Source('interrupts.cc')
    Source('isa.cc')
    Source('linux/linux.cc')
    Source('linux/process.cc')
    Source('linux/syscalls.cc')
    Source('nativetrace.cc')
    Source('pagetable.cc')
    Source('process.cc')
    Source('remote_gdb.cc')
    Source('solaris/process.cc')
    Source('solaris/solaris.cc')
    Source('system.cc')
    Source('tlb.cc')
    Source('ua2005.cc')
    Source('utility.cc')
    Source('vtophys.cc')

    SimObject('SparcInterrupts.py')
    SimObject('SparcISA.py')
    SimObject('SparcNativeTrace.py')
    SimObject('SparcSystem.py')
    SimObject('SparcTLB.py')

    DebugFlag('Sparc', "Generic SPARC ISA stuff")
    DebugFlag('RegisterWindows', "Register window manipulation")

    ISADesc('isa/main.isa')
