# Copyright 2025 Google, Inc.
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "config",
    srcs = ["config.py"],
    deps = [
        ":defines",
        ":io",
        ":types",
        "@Kconfiglib//:kconfiglib",
    ],
)

py_binary(
    name = "sync",
    srcs = ["sync.py"],
    args = ["$(execpath @buildifier_prebuilt//buildifier:buildifier)"],
    data = ["@buildifier_prebuilt//buildifier"],
    deps = [
        ":config",
        ":io",
        ":scons",
    ],
)

py_library(
    name = "scons",
    srcs = ["scons.py"],
    deps = [
        ":config",
        ":defines",
        ":dependency_scanner",
        ":io",
        ":types",
        ":workarounds",
    ],
)

py_library(
    name = "dependency_scanner",
    srcs = ["dependency_scanner.py"],
    deps = [
        ":defines",
        ":types",
    ],
)

py_library(
    name = "io",
    srcs = ["io.py"],
)

py_library(
    name = "types",
    srcs = ["types.py"],
)

py_library(
    name = "workarounds",
    srcs = ["workarounds.py"],
)

py_library(
    name = "defines",
    srcs = ["defines.py"],
)
