# Copyright 2025 Google, Inc.
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""BUILD file writer and utilities."""

import logging
import os

from scons2bzl import types

GENERATED_FILE_MARKER = "# GENERATED BY @bazelize_gem5//scons2bzl:sync"
NEW_FILE_TEMPLATE = """
# See "build_tools/bazel/README.md" when in doubt
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag", "string_flag", "int_flag")
load(
    "//build_tools/bazel:rules.bzl",
    "gem5_py_source",
    "gen_config",
    "debug_flag",
    "COMMON_COPTS",
    "COMMON_LINKOPTS",
)
load("//build_tools/bazel:macro.bzl", "macro_sim_object", "macro_py_source")

cc_library(
    name = "lib",
    deps = [
# OBJS_GOES_HERE.START
# OBJS_GOES_HERE.END
    ],
    visibility = ["//build_tools/bazel/package_group:simulator"],
)

sim_objects = [
# SIMOBJ_GOES_HERE.START
# SIMOBJ_GOES_HERE.END
]

cc_library(
    name = "sim_objects",
    deps = sim_objects + [
# SIMOBJ_LIB_GOES_HERE.START
# SIMOBJ_LIB_GOES_HERE.END
    ],
    visibility = ["//build_tools/bazel/package_group:simulator"],
)

# DEBUG_FLAG_GOES_HERE.START
# DEBUG_FLAG_GOES_HERE.END

# TARGET_GOES_HERE.START
# TARGET_GOES_HERE.END
""".lstrip()
TARGET_ENTRY_TEMPLATE = """
cc_library(
    name = "{name}",
    srcs = [{srcs}],
    hdrs = [{hdrs}],
    deps = [{deps}],
    copts = COMMON_COPTS + [{copts}],
    alwayslink = True,  # Extra care needs to be taken on `deps` ordering to remove this
    include_prefix = "{prefix}",
    visibility = ["//build_tools/bazel/package_group:simulator"],
)
""".strip()
AUX_TARGET_TEMPLATE = r"""
genrule(
    name = "{name}",
    srcs = ["{src}"],
    outs = ["{out}"],
    cmd = "cp \"$<\" \"$@\"",
)
""".strip()
SIMOBJ_ENTRY_TEMPLATE = (
    'macro_sim_object("{file}", sim_objects=[{sim_objects}], enums=[{enums}]),'
)
DEBUG_FLAG_ENTRY_TEMPLATE = """
debug_flag(
    name="{name}",
    description="{desc}",
    flags=[{flags}],
    is_fmt={is_fmt},
)
""".strip()
CONFIG_HDR_ENTRY_TEMPLATE = 'gen_config(name = "{config}", {decl})'
CONFIG_FLAG_ENTRY_TEMPLATE = """
{config_type}_flag(
    name = "{target_name}",
    build_setting_default = {default},
)""".strip()
CONFIG_SETTING_ENTRY_TEMPLATE = """
config_setting(
    name = "{target_name}_is_true",
    flag_values = {{":{target_name}": "True"}},
)""".strip()


def new_file_template(file: str) -> None:
    new_content = "\n".join([GENERATED_FILE_MARKER, NEW_FILE_TEMPLATE])
    if not os.path.isdir(os.path.dirname(file)):
        os.makedirs(os.path.dirname(file))
    with open(file, "w") as f:
        f.write(new_content)


def update_build(
    build_file: types.Path,
    marker: str,
    content: str,
    append: bool = True,
    no_error: bool = False,
) -> None:
    """The utility to create/update a generated BUILD file.

    This function assumes the template contains several insertion points
    indicated by `marker`.  For example, a generated BUILD file may contain
    something like:

    ```
    # ... contents before the insertion point ...
    # MY_MARKER.START
    # MY_MARKER.END
    # ... contents after the insertion point ...
    ```

    Args:
        build_file: Path to the build_file.
        marker: Indicator of the location in the file where `content` should be
          injected.
        content: The content to be written.
        append: Overwrite the file if `False`.
        no_error: Do nothing on error.

    Raises:
        ValueError: If the `marker` indicating the location to inject `context`
          cannot be found.
    """
    build_file = build_file.abs
    if not os.path.isfile(build_file):
        new_file_template(build_file)
    with open(build_file) as f:
        lines = f.readlines()
    try:
        start = lines.index(f"# {marker}.START\n")
        end = lines.index(f"# {marker}.END\n")
    except ValueError:
        if no_error:
            return
        logging.error("Error updating %s", build_file)
        raise
    if content:
        content_lines = [content + "\n"]
    else:
        content_lines = []
    begin = end if append else start + 1
    new_content = "".join(lines[:begin] + content_lines + lines[end:])
    with open(build_file, "w") as f:
        f.write(new_content)


def remove_if_generated(file: types.Path) -> None:
    with open(file.abs) as f:
        is_generated = f.readline().startswith(GENERATED_FILE_MARKER)
    if is_generated:
        os.remove(file.abs)
