#!/usr/bin/env python3
# Copyright 2025 Google, Inc.
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""The tool to generate BUILD files for the gem5 project.

Usage: bazel run @bazelize_gem5/scons2bzl:sync
"""

# NOTE: This script is a workaround before SCons being deprecated.
# Before that, Bazel BUILD files are treated as shadow copies of SConscripts
# and to be generated by this script

# NOTE: This implementation is a POC of an instance of implementation choice
# realization

import argparse
import logging
import os

from scons2bzl import config
from scons2bzl.scons import SConstruct
from scons2bzl.types import Path


def main():
    logging.basicConfig(level=logging.INFO)
    parser = argparse.ArgumentParser()
    parser.add_argument("buildifier_bin")
    parser.add_argument("--allow-code-execution", action="store_true")
    args = parser.parse_args()

    if "BUILD_WORKSPACE_DIRECTORY" not in os.environ:
        raise RuntimeError("Need to invoke using `bazel run ...`")
    gem5_home = os.environ["BUILD_WORKSPACE_DIRECTORY"]
    buildifier_bin = os.path.join(gem5_home, args.buildifier_bin)
    assert os.path.isfile(buildifier_bin)

    if not args.allow_code_execution:
        raise RuntimeError(
            "This tool uses `exec()` on SConscript and SimObject "
            "parameter files.  Specify --allow-code-execution to "
            "allow this."
        )
    scons = SConstruct(os.path.join(gem5_home, Path.SCONSTRUCT))
    scons.bazelize(args.allow_code_execution)

    # Generate bazel configurations from Kconfig
    logging.info("Scanning Kconfig files")
    configs = config.read_kconfig(gem5_home)
    config.update_build_files(gem5_home, configs)

    scons.finalize()

    logging.info("Running buildifier")
    os.system(f"{buildifier_bin} $(find {gem5_home}/src -name BUILD.bazel)")

    logging.info("Done")


if __name__ == "__main__":
    main()
