# -*- mode:python -*-

# Copyright (c) 2004-2005 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import sys
from os.path import isdir

# Import build environment variable from SConstruct.
Import('env')

###################################################
#
# Define needed sources.
#
###################################################

# Base sources used by all configurations.
arch_base_sources = Split('''
	arch/sparc/decoder.cc
        arch/sparc/alpha_o3_exec.cc
	arch/sparc/fast_cpu_exec.cc
	arch/sparc/simple_cpu_exec.cc
	arch/sparc/full_cpu_exec.cc
	arch/sparc/faults.cc
	arch/sparc/isa_traits.cc
	''')

# Full-system sources
arch_full_system_sources = Split('''
	arch/sparc/alpha_memory.cc
	arch/sparc/arguments.cc
	arch/sparc/ev5.cc
	arch/sparc/osfpal.cc
	arch/sparc/stacktrace.cc
	arch/sparc/vtophys.cc
	''')

# Syscall emulation (non-full-system) sources
arch_syscall_emulation_sources = Split('''
	arch/sparc/alpha_common_syscall_emul.cc
	arch/sparc/alpha_linux_process.cc
	arch/sparc/alpha_tru64_process.cc
	''')

sources = arch_base_sources

if env['FULL_SYSTEM']:
    sources += arch_full_system_sources
    if env['ALPHA_TLASER']:
        sources += arch_turbolaser_sources
else:
    sources += arch_syscall_emulation_sources

for opt in env.ExportOptions:
    env.ConfigFile(opt)

Return('sources')
