#ifndef __MEM_RUBY_NETWORK_GARNET_FIXED_PIPELINE_ROUTING_ROUTING_HH__
#define __MEM_RUBY_NETWORK_GARNET_FIXED_PIPELINE_ROUTING_ROUTING_HH__

#include <iostream>
#include <vector>

class Routing
{
};


#endif // __MEM_RUBY_NETWORK_GARNET_FIXED_PIPELINE_ROUTING_ROUTING_HH__