# Copyright 2025 Google, Inc.
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cat << EOF
#
# DO NOT EDIT THIS FILE!
# File automatically generated by
#   /usr/local/google/home/hchsiao/gem5/src/SConscript:617
#

buildEnv = {'HAVE_PROTOBUF': True, 'HAVE_FENV': True, 'HAVE_PNG': True, 'HAVE_POSIX_CLOCK': True, 'HAVE_VALGRIND': False, 'HAVE_DEPRECATED_NAMESPACE': True, 'HAVE_HDF5': False, 'KVM_ISA': 'x86', 'BUILD_TLM': False, 'HAVE_TUNTAP': True, 'HAVE_CAPSTONE': True, 'HAVE_KVM': False, 'HAVE_PERF_ATTR_EXCLUDE_HOST': 1, 'HAVE_SYSTEMC': False, 'BATCH': False, 'BATCH_CMD': '', 'M5_BUILD_CACHE': '', 'USE_EFENCE': False, 'USE_POSIX_CLOCK': False, 'RUBY': True, 'USE_MULTIPLE_PROTOCOLS': True, 'PROTOCOL': 'MI_example', 'RUBY_PROTOCOL_GPU_VIPER': False, 'RUBY_PROTOCOL_MOESI_AMD_Base': False, 'RUBY_PROTOCOL_MESI_Two_Level': False, 'RUBY_PROTOCOL_MESI_Three_Level': False, 'RUBY_PROTOCOL_MESI_Three_Level_HTM': False, 'RUBY_PROTOCOL_MI_example': True, 'RUBY_PROTOCOL_MOESI_CMP_directory': False, 'RUBY_PROTOCOL_MOESI_CMP_token': False, 'RUBY_PROTOCOL_MOESI_hammer': False, 'RUBY_PROTOCOL_Garnet_standalone': False, 'RUBY_PROTOCOL_CHI': False, 'RUBY_PROTOCOL_MSI': False, 'SLICC_HTML': False, 'NUMBER_BITS_PER_SET': 64, 'TARGET_GPU_ISA': '', 'VEGA_GPU_ISA': False, 'BUILD_ISA': True, 'USE_ARM_ISA': False, 'USE_ARM_FASTMODEL': False, 'PVLIB_HOME': '', 'PVLIB_FLAVOR': '', 'MAXCORE_HOME': '', 'ARMLMD_LICENSE_FILE': '', 'ARMLMD_LICENSE_COUNT': 0, 'SIMGEN': '', 'USE_MIPS_ISA': False, 'USE_POWER_ISA': False, 'USE_RISCV_ISA': True, 'USE_SPARC_ISA': False, 'USE_X86_ISA': False, 'USE_KVM': False, 'USE_CAPSTONE': False, 'USE_SYSTEMC': False, 'BUILD_GPU': False, 'USE_TEST_OBJECTS': False}
EOF
