# Copyright 2025 Google, Inc.
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cat << EOF
// this file is auto-generated by util/cpt_upgrader.py
#include <string>
#include <set>

namespace gem5
{

std::set<std::string> version_tags = {
  "arm-ccregs",
  "arm-contextidr-el2",
  "arm-gem5-gic-ext",
  "arm-gicv2-banked-regs",
  "arm-hdlcd-upgrade",
  "arm-miscreg-teehbr",
  "arm-sve",
  "arm-sysreg-mapping-ns",
  "armv8",
  "cpu-pid",
  "dvfs-perflevel",
  "etherswitch",
  "globals-to-root",
  "ide-dma-abort",
  "isa-is-simobject",
  "memory-per-range",
  "mempool-sections",
  "mempool-to-seworkload",
  "multiple-event-queues",
  "process-fdmap-rename",
  "register-files",
  "remove-arm-cpsr-mode-miscreg",
  "riscv-dyn-vlen",
  "riscv-pcstate",
  "riscv-vext",
  "ruby-block-size-bytes",
  "smt-interrupts",
  "x86-add-tlb",
  "x86-add-xcr0",
};

} // namespace gem5
EOF
