# Copyright (c) 2025 Akanksha Chaudhari, Matt Sinclair
# (University of Wisconsin-Madison)
# All rights reserved.
#
# This file contains modifications and/or code derived from:
# gem5-SALAM: https://github.com/TeCSAR-UNCC/gem5-SALAM
#
# The license below extends only to copyright in the software and shall
# not be construed as granting a license to any other intellectual
# property including but not limited to intellectual property relating
# to a hardware implementation of the functionality of the software
# licensed hereunder.  You may use the software subject to the license
# terms below provided that you ensure that this notice is replicated
# unmodified and in its entirety in all distributions of the software,
# modified or unmodified, in source code or in binary form.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import("*")

# --with-salam generates sources from the selected hardware profile.
# The profile YAML is env['SALAM_HW_CONFIG']. Products are written
# under generated/salam and registered from there.
if env["CONF"]["USE_ARM_ISA"] and env["CONF"].get("WITH_SALAM", False):

    import sys

    from gem5_scons import Transform, error

    SimObject("CommInterface.py", sim_objects=["CommInterface"])
    SimObject("ScratchpadMemory.py", sim_objects=["ScratchpadMemory"])
    SimObject("NoncoherentDma.py", sim_objects=["NoncoherentDma"])
    SimObject("StreamDma.py", sim_objects=["StreamDma"])
    SimObject("AccCluster.py", sim_objects=["AccCluster"])
    SimObject("StreamBuffer.py", sim_objects=["StreamBuffer"])
    SimObject("RegisterBank.py", sim_objects=["RegisterBank"])

    SimObject("AccComputeUnit.py", sim_objects=["AccComputeUnit"])
    SimObject("LLVMInterface.py", sim_objects=["LLVMInterface"])

    SimObject("CycleCounts.py", sim_objects=["CycleCounts"])

    if not env.get("SALAM_HW_CONFIG"):
        error("SALAM build is missing its hardware profile")
    generator = Dir("#util/SALAM-tools/hw_generator").abspath
    if generator not in sys.path:
        sys.path.insert(0, generator)
    try:
        import SALAMGeneratedSources
    except ImportError:
        error(
            "PyYAML is required for SALAM builds; on Ubuntu it is "
            "provided by python3-yaml."
        )
    try:
        inputs = SALAMGeneratedSources.load_source_config(
            env["SALAM_HW_CONFIG"]
        )
        generated = SALAMGeneratedSources.load_generated_sources(inputs)
        SALAMGeneratedSources.require_compatible_functional_units(
            generated
        )
    except SALAMGeneratedSources.SourceConfigError as exc:
        error(str(exc))
    generated_dir = Dir("generated")
    salam_out = generated_dir.Dir("salam")
    env.Prepend(CPPPATH=[generated_dir])
    content = [salam_out.File(rel) for rel in generated.generated_paths()]
    sources = [
        File(inputs.config_path),
        File(inputs.instructions),
        File("#util/SALAM-tools/hw_generator/SALAMGeneratedSources.py"),
        File("#util/SALAM-tools/hw_generator/SALAMClassGenerator.py"),
        Value("\n".join(generated.generated_paths())),
    ]
    sources.extend(File(path) for path in generated.fu_input_paths)
    env.Command(
        content,
        sources,
        MakeAction(
            SALAMGeneratedSources.generate_sources_action,
            Transform("SALAM GEN", 0),
        ),
    )
    SimObject(
        salam_out.File("FunctionalUnits.py"),
        sim_objects=list(generated.fu_class_names),
    )
    SimObject(
        salam_out.File("InstConfig.py"),
        sim_objects=list(generated.instruction_class_names),
    )
    generated_cc = [node for node in content if str(node).endswith(".cc")]

    SimObject("HWInterface.py", sim_objects=["HWInterface"])
    SimObject("HWStatistics.py", sim_objects=["HWStatistics"])
    SimObject("InstOpCodes.py", sim_objects=["InstOpCodes"])
    SimObject("SALAMPowerModel.py", sim_objects=["SALAMPowerModel"])
    SimObject("SimulatorConfig.py", sim_objects=["SimulatorConfig"])


    Source("comm_interface.cc")
    Source("acc_compute_unit.cc")
    Source("llvm_interface.cc")
    Source("dma_write_fifo.cc")
    Source("noncoherent_dma.cc")
    Source("stream_dma.cc")
    Source("acc_cluster.cc")
    Source("stream_buffer.cc")
    Source("stream_port.cc")
    Source("scratchpad_memory.cc")
    Source("register_bank.cc")

    Source("LLVMRead/value.cc")
    Source("LLVMRead/function.cc")
    Source("LLVMRead/basic_block.cc")
    Source("LLVMRead/debug_flags.cc")
    Source("LLVMRead/mem_request.cc")
    Source("LLVMRead/instruction.cc")
    Source("LLVMRead/registers.cc")
    Source("LLVMRead/operand.cc")

    Source("HWModeling/cycle_counts.cc")
    for node in generated_cc:
        Source(node)
    Source("HWModeling/hw_interface.cc")
    Source("HWModeling/hw_statistics.cc")
    Source("HWModeling/opcodes.cc")
    Source("HWModeling/salam_power_model.cc")
    Source("HWModeling/simulator_config.cc")

    DebugFlag("CommInterface")
    DebugFlag("CommInterfaceQueues")
    DebugFlag("DeviceMMR")
    DebugFlag("LLVMInterface")
    DebugFlag("NoncoherentDma")
    DebugFlag("LLVMParse")
    DebugFlag("Runtime")
    DebugFlag("RuntimeCompute")
    DebugFlag("RuntimeQueues")
    DebugFlag("SALAM_Debug")
    DebugFlag("StreamBuffer")
    DebugFlag("StreamDma")
    DebugFlag("Trace")
    DebugFlag("Step")

    CompoundFlag(
        "JDEV",
        [
            "LLVMInterface",
            "CommInterface",
            "Runtime",
            "RuntimeCompute",
            "RuntimeQueues",
            "SALAM_Debug",
        ],
    )
    CompoundFlag("SALAM", ["CommInterface", "LLVMInterface"])
