#include "bootcamp/hello-sim-object/hello_sim_object.hh"

#include <iostream>

// This is a autogenerated file. \
// It will be created due to definition of debug flags in SConscript
#include "debug/HelloExampleFlag.hh"

// a bunch of macro to be used for debug flags \
// are defined in base/trace.hh e.g. DPRINTF
#include "base/trace.hh"

namespace gem5
{

HelloSimObject::HelloSimObject(const HelloSimObjectParams& params):
SimObject(params),
goodByeObject(params.goodbye_object),
remainingHellosToPrintByEvent(params.num_hellos),
nextHelloEvent([this](){ processNextHelloEvent();}, name()+"nextHelloEvent")
{
// fatal and fatal_if are gem5 keywords
if (params.num_hellos < 0) {
    fatal("1. we can not print negative number of times");
}
fatal_if(params.num_hellos < 0, \
        "2. we can not print negative number of times");

for (int i = 0; i < params.num_hellos; i = i + 1){
std::cout<<"Hello World Constructor of \
    HelloSimObject from Gem5"<<std::endl;
}
DPRINTF(HelloExampleFlag,\
    "%s: Hello World Constructor of HelloSimObject from Gem5\n",__func__);
}

void
HelloSimObject::processNextHelloEvent()
{
std::cout<<"tick: "<<curTick()<<\
    ", Hello from HelloSimObject::processNextHelloEvent"<<std::endl;
remainingHellosToPrintByEvent--;
if (remainingHellosToPrintByEvent > 0){
    schedule(nextHelloEvent, curTick() + 201);
}
if (remainingHellosToPrintByEvent == 0) {
    //schedule(goodByeObject->sayGoodBye(), curTick()+2);
    goodByeObject->sayGoodBye();
}
}

// the startup is by default called by the simulator at tick=0
void
HelloSimObject::startup()
{
    panic_if((curTick() != 0), "startup called at a tick other than 0");

panic_if(nextHelloEvent.scheduled(), "nextHelloEvent is scheduled before \
HelloSimObject::startup is called");
schedule(nextHelloEvent, curTick()+202);
}

}	// namespace gem5
