# -*- mode:python -*-

# Copyright (c) 2018 Inria
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

SimObject('ReplacementPolicies.py', sim_objects=[
    'BaseReplacementPolicy', 'DuelingRP', 'FIFORP', 'SecondChanceRP',
    'LFURP', 'LRURP', 'BIPRP', 'MRURP', 'RandomRP', 'BRRIPRP', 'SHiPRP',
    'SHiPMemRP', 'SHiPPCRP', 'TreePLRURP', 'WeightedLRURP'])

Source('bip_rp.cc')
Source('brrip_rp.cc')
Source('dueling_rp.cc')
Source('fifo_rp.cc')
Source('lfu_rp.cc')
Source('lru_rp.cc')
Source('mru_rp.cc')
Source('random_rp.cc')
Source('second_chance_rp.cc')
Source('ship_rp.cc')
Source('tree_plru_rp.cc')
Source('weighted_lru_rp.cc')

# The common replacement policy base class (replacement_policy::Base) now
# gathers profiling statistics. Instantiating any policy therefore pulls in
# the statistics implementation and its dependencies, none of which are part
# of the 'gem5 simobject' tag. The unit tests below must link them explicitly,
# and the 'socket_test' tag is reused to pull in the zlib (-lz) dependency
# required by base/output.cc.
stats_srcs = [
    '../../../base/statistics.cc',
    '../../../base/stats/info.cc',
    '../../../base/stats/storage.cc',
    '../../../base/time.cc',
    '../../../base/hostinfo.cc',
    '../../../base/output.cc',
    '../../../sim/core.cc',
    '../../../sim/root.cc',
    '../../../sim/globals.cc',
    '../../../sim/tags.cc',
]
stats_tags = [with_tag('gem5 simobject'), with_tag('socket_test')]

GTest('replaceable_entry.test', 'replaceable_entry.test.cc')
GTest('base_rp.test', 'lru_rp.cc', 'base_rp.test.cc', *stats_srcs,
    *stats_tags)
GTest('tree_plru_rp.test', 'tree_plru_rp.cc', 'tree_plru_rp.test.cc',
    *stats_srcs, *stats_tags)
GTest('fifo_rp.test', 'fifo_rp.cc', 'fifo_rp.test.cc', *stats_srcs,
    *stats_tags)
GTest('lfu_rp.test', 'lfu_rp.cc', 'lfu_rp.test.cc', *stats_srcs, *stats_tags)
GTest('lru_rp.test', 'lru_rp.cc', 'lru_rp.test.cc', *stats_srcs, *stats_tags)
GTest('mru_rp.test', 'mru_rp.cc', 'mru_rp.test.cc', *stats_srcs, *stats_tags)
GTest('second_chance_rp.test', 'fifo_rp.cc', 'second_chance_rp.cc',
    'second_chance_rp.test.cc', *stats_srcs, *stats_tags)
