"""Comprehensive list of all gem5 debug flag targets.

Used by sim_object_params_srcs to provide all debug/*.hh generated headers
on the include path. The generated pybind .cc files include source headers
(e.g., sim/sim_object.hh -> sim/eventq.hh -> debug/Event.hh) that
transitively pull in debug flag headers.

This list must be kept in sync with gem5_debug_flag(), gem5_compound_flag(),
and gem5_debug_format_flag() declarations across all BUILD.bazel files.
"""

ALL_DEBUG_FLAGS = [
    # src/base
    "//src/base:Annotate",
    "//src/base:AnnotateAll",
    "//src/base:AnnotateQ",
    "//src/base:AnnotateVerbose",
    "//src/base:FmtFlag",
    "//src/base:FmtStackTrace",
    "//src/base:FmtTicksOff",
    "//src/base:GDBAcc",
    "//src/base:GDBAll",
    "//src/base:GDBExtra",
    "//src/base:GDBMisc",
    "//src/base:GDBRead",
    "//src/base:GDBRecv",
    "//src/base:GDBSend",
    "//src/base:GDBWrite",
    "//src/base:SQL",
    "//src/base:StatEvents",
    "//src/base:Stats",
    "//src/base:VNC",

    # src/sim
    "//src/sim:Checkpoint",
    "//src/sim:ClockDomain",
    "//src/sim:Config",
    "//src/sim:CxxConfig",
    "//src/sim:DVFS",
    "//src/sim:Drain",
    "//src/sim:EnteringEventQueue",
    "//src/sim:Event",
    "//src/sim:ExternalSignal",
    "//src/sim:Flow",
    "//src/sim:IPI",
    "//src/sim:IPR",
    "//src/sim:Interrupt",
    "//src/sim:Loader",
    "//src/sim:PowerDomain",
    "//src/sim:ProbeVerbose",
    "//src/sim:PseudoInst",
    "//src/sim:Stack",
    "//src/sim:SyscallAll",
    "//src/sim:SyscallBase",
    "//src/sim:SyscallVerbose",
    "//src/sim:ThermalDomain",
    "//src/sim:Thread",
    "//src/sim:TimeSync",
    "//src/sim:Timer",
    "//src/sim:Vma",
    "//src/sim:VoltageDomain",
    "//src/sim:VtoPhys",
    "//src/sim:WorkItems",

    # src/mem
    "//src/mem:AddrRanges",
    "//src/mem:BaseXBar",
    "//src/mem:Bridge",
    "//src/mem:CFI",
    "//src/mem:Cache",
    "//src/mem:CacheAll",
    "//src/mem:CacheComp",
    "//src/mem:CachePort",
    "//src/mem:CacheRepl",
    "//src/mem:CacheTags",
    "//src/mem:CacheVerbose",
    "//src/mem:CoherentXBar",
    "//src/mem:CommMonitor",
    "//src/mem:DRAM",
    "//src/mem:DRAMPower",
    "//src/mem:DRAMSim2",
    "//src/mem:DRAMState",
    "//src/mem:DRAMsim3",
    "//src/mem:ExternalPort",
    "//src/mem:HMCController",
    "//src/mem:HWPrefetch",
    "//src/mem:HWPrefetchQueue",
    "//src/mem:HtmMem",
    "//src/mem:LLSC",
    "//src/mem:MMU",
    "//src/mem:MSHR",
    "//src/mem:MemChecker",
    "//src/mem:MemCheckerMonitor",
    "//src/mem:MemCtrl",
    "//src/mem:MemoryAccess",
    "//src/mem:NVM",
    "//src/mem:NoncoherentXBar",
    "//src/mem:PacketQueue",
    "//src/mem:PartitionPolicy",
    "//src/mem:PortTrace",
    "//src/mem:QOS",
    "//src/mem:ResponsePort",
    "//src/mem:SerialLink",
    "//src/mem:SnoopFilter",
    "//src/mem:StackDist",
    "//src/mem:SysBridge",
    "//src/mem:TokenPort",
    "//src/mem:XBar",

    # src/mem/ruby
    "//src/mem/ruby:ProtocolTrace",
    "//src/mem/ruby:Ruby",
    "//src/mem/ruby:RubyCache",
    "//src/mem/ruby:RubyCacheTrace",
    "//src/mem/ruby:RubyDma",
    "//src/mem/ruby:RubyGenerated",
    "//src/mem/ruby:RubyHitMiss",
    "//src/mem/ruby:RubyNetwork",
    "//src/mem/ruby:RubyPort",
    "//src/mem/ruby:RubyPrefetcher",
    "//src/mem/ruby:RubyProtocol",
    "//src/mem/ruby:RubyQueue",
    "//src/mem/ruby:RubyResourceStalls",
    "//src/mem/ruby:RubySequencer",
    "//src/mem/ruby:RubySlicc",
    "//src/mem/ruby:RubyStats",
    "//src/mem/ruby:RubySystem",
    "//src/mem/ruby:RubyTester",

    # src/cpu
    "//src/cpu:Activity",
    "//src/cpu:BAC",
    "//src/cpu:BTB",
    "//src/cpu:Branch",
    "//src/cpu:Checker",
    "//src/cpu:Commit",
    "//src/cpu:CommitRate",
    "//src/cpu:Context",
    "//src/cpu:Decode",
    "//src/cpu:DirectedTest",
    "//src/cpu:DynInst",
    "//src/cpu:ElasticTrace",
    "//src/cpu:EpisodeCount",
    "//src/cpu:Exec",
    "//src/cpu:ExecAll",
    "//src/cpu:ExecAsid",
    "//src/cpu:ExecCPSeq",
    "//src/cpu:ExecEffAddr",
    "//src/cpu:ExecEnable",
    "//src/cpu:ExecFaulting",
    "//src/cpu:ExecFetchSeq",
    "//src/cpu:ExecFlags",
    "//src/cpu:ExecKernel",
    "//src/cpu:ExecMacro",
    "//src/cpu:ExecMicro",
    "//src/cpu:ExecNoTicks",
    "//src/cpu:ExecOpClass",
    "//src/cpu:ExecRegDelta",
    "//src/cpu:ExecResult",
    "//src/cpu:ExecSymbol",
    "//src/cpu:ExecThread",
    "//src/cpu:ExecUser",
    "//src/cpu:FTQ",
    "//src/cpu:Fetch",
    "//src/cpu:FreeList",
    "//src/cpu:GUPSGen",
    "//src/cpu:GarnetSyntheticTraffic",
    "//src/cpu:HtmCpu",
    "//src/cpu:IEW",
    "//src/cpu:IQ",
    "//src/cpu:Indirect",
    "//src/cpu:InstTracker",
    "//src/cpu:InvalidReg",
    "//src/cpu:Kvm",
    "//src/cpu:KvmAll",
    "//src/cpu:KvmContext",
    "//src/cpu:KvmIO",
    "//src/cpu:KvmInt",
    "//src/cpu:KvmRun",
    "//src/cpu:KvmTimer",
    "//src/cpu:LSQ",
    "//src/cpu:LSQUnit",
    "//src/cpu:LTage",
    "//src/cpu:LooppointAnalysis",
    "//src/cpu:MemDepUnit",
    "//src/cpu:MemTest",
    "//src/cpu:Minor",
    "//src/cpu:MinorCPU",
    "//src/cpu:MinorExecute",
    "//src/cpu:MinorInterrupt",
    "//src/cpu:MinorMem",
    "//src/cpu:MinorScoreboard",
    "//src/cpu:MinorTiming",
    "//src/cpu:MinorTrace",
    "//src/cpu:Mwait",
    "//src/cpu:O3CPU",
    "//src/cpu:O3CPUAll",
    "//src/cpu:O3PipeView",
    "//src/cpu:PCEvent",
    "//src/cpu:PcCountTracker",
    "//src/cpu:ProtocolTest",
    "//src/cpu:Quiesce",
    "//src/cpu:RAS",
    "//src/cpu:ROB",
    "//src/cpu:Rename",
    "//src/cpu:RubyTest",
    "//src/cpu:Scoreboard",
    "//src/cpu:SimpleCPU",
    "//src/cpu:SimpleTrace",
    "//src/cpu:SpatterGen",
    "//src/cpu:SpatterKernel",
    "//src/cpu:StoreSet",
    "//src/cpu:Tage",
    "//src/cpu:TageSCL",
    "//src/cpu:TraceCPUData",
    "//src/cpu:TraceCPUInst",
    "//src/cpu:TrafficGen",
    "//src/cpu:Writeback",

    # src/dev
    "//src/dev:DMA",
    "//src/dev:DMACopyEngine",
    "//src/dev:DiskImageAll",
    "//src/dev:DiskImageRead",
    "//src/dev:DiskImageWrite",
    "//src/dev:DistEthernet",
    "//src/dev:DistEthernetCmd",
    "//src/dev:DistEthernetPkt",
    "//src/dev:Ethernet",
    "//src/dev:EthernetAll",
    "//src/dev:EthernetCksum",
    "//src/dev:EthernetDMA",
    "//src/dev:EthernetData",
    "//src/dev:EthernetDesc",
    "//src/dev:EthernetEEPROM",
    "//src/dev:EthernetIntr",
    "//src/dev:EthernetNoData",
    "//src/dev:EthernetPIO",
    "//src/dev:EthernetSM",
    "//src/dev:IdeAll",
    "//src/dev:IdeCtrl",
    "//src/dev:IdeDisk",
    "//src/dev:IntPin",
    "//src/dev:Intel8254Timer",
    "//src/dev:IsaFake",
    "//src/dev:MC146818",
    "//src/dev:PS2",
    "//src/dev:PciDevice",
    "//src/dev:PciHost",
    "//src/dev:PciUpstream",
    "//src/dev:QemuFwCfg",
    "//src/dev:QemuFwCfgVerbose",
    "//src/dev:SimpleDisk",
    "//src/dev:SimpleDiskData",
    "//src/dev:Terminal",
    "//src/dev:TerminalVerbose",
    "//src/dev:Uart",
    "//src/dev:VIO",
    "//src/dev:VIO9P",
    "//src/dev:VIO9PData",
    "//src/dev:VIOBlock",
    "//src/dev:VIOConsole",
    "//src/dev:VIOIface",
    "//src/dev:VIORng",

    # src/dev/arm
    "//src/dev/arm:AMBA",
    "//src/dev/arm:EnergyCtrl",
    "//src/dev/arm:FVPBasePwrCtrl",
    "//src/dev/arm:FlashDevice",
    "//src/dev/arm:GIC",
    "//src/dev/arm:GICV2M",
    "//src/dev/arm:HDLcd",
    "//src/dev/arm:ITS",
    "//src/dev/arm:MHU",
    "//src/dev/arm:NoMali",
    "//src/dev/arm:PL111",
    "//src/dev/arm:Pl050",
    "//src/dev/arm:RVCTRL",
    "//src/dev/arm:SCMI",
    "//src/dev/arm:SMMUv3",
    "//src/dev/arm:SMMUv3Hazard",
    "//src/dev/arm:Sp805",
    "//src/dev/arm:UFSHostDevice",
    "//src/dev/arm:VGIC",

    # src/dev/amdgpu
    "//src/dev/amdgpu:AMDGPUDevice",
    "//src/dev/amdgpu:AMDGPUMem",
    "//src/dev/amdgpu:AMDGPUSystemHub",
    "//src/dev/amdgpu:PM4PacketProcessor",
    "//src/dev/amdgpu:SDMAData",
    "//src/dev/amdgpu:SDMAEngine",

    # src/dev/hsa
    "//src/dev/hsa:HSAPacketProcessor",

    # src/dev/riscv
    "//src/dev/riscv:Clint",
    "//src/dev/riscv:LupioBLK",
    "//src/dev/riscv:LupioIPI",
    "//src/dev/riscv:LupioPIC",
    "//src/dev/riscv:LupioRNG",
    "//src/dev/riscv:LupioRTC",
    "//src/dev/riscv:LupioSYS",
    "//src/dev/riscv:LupioTMR",
    "//src/dev/riscv:LupioTTY",
    "//src/dev/riscv:Plic",
    "//src/dev/riscv:VirtIOMMIO",

    # src/dev/x86
    "//src/dev/x86:CMOS",
    "//src/dev/x86:I8042",
    "//src/dev/x86:I82094AA",
    "//src/dev/x86:I8237",
    "//src/dev/x86:I8254",
    "//src/dev/x86:I8259",
    "//src/dev/x86:PcSpeaker",

    # src/dev/sparc
    "//src/dev/sparc:Iob",

    # src/dev/mips
    "//src/dev/mips:Malta",

    # src/kern
    "//src/kern:DebugPrintf",
    "//src/kern:Printf",

    # src/arch
    "//src/arch:CCRegs",
    "//src/arch:Decoder",
    "//src/arch:Faults",
    "//src/arch:FloatRegs",
    "//src/arch:IntRegs",
    "//src/arch:MatRegs",
    "//src/arch:MiscRegs",
    "//src/arch:Registers",
    "//src/arch:TLBVerbose",
    "//src/arch:VecPredRegs",
    "//src/arch:VecRegs",

    # src/arch/generic
    "//src/arch/generic:PageTableWalker",
    "//src/arch/generic:Semihosting",
    "//src/arch/generic:TLB",

    # src/arch/x86
    "//src/arch/x86:ACPI",
    "//src/arch/x86:LocalApic",
    "//src/arch/x86:X86",

    # src/arch/arm
    "//src/arch/arm:Arm",
    "//src/arch/arm:ArmTme",
    "//src/arch/arm:MPAM",
    "//src/arch/arm:PMUVerbose",

    # src/arch/riscv
    "//src/arch/riscv:PMP",
    "//src/arch/riscv:RiscvMisc",

    # src/arch/sparc
    "//src/arch/sparc:RegisterWindows",
    "//src/arch/sparc:Sparc",

    # src/arch/power
    "//src/arch/power:Power",

    # src/arch/mips
    "//src/arch/mips:MipsPRA",

    # src/arch/amdgpu
    "//src/arch/amdgpu:GPUPTWalker",
    "//src/arch/amdgpu:VEGA",

    # src/gpu-compute
    "//src/gpu-compute:GPUALL",
    "//src/gpu-compute:GPUAgentDisp",
    "//src/gpu-compute:GPUCoalescer",
    "//src/gpu-compute:GPUCommandProc",
    "//src/gpu-compute:GPUDisp",
    "//src/gpu-compute:GPUDriver",
    "//src/gpu-compute:GPUExec",
    "//src/gpu-compute:GPUFetch",
    "//src/gpu-compute:GPUInitAbi",
    "//src/gpu-compute:GPUInst",
    "//src/gpu-compute:GPUKernelInfo",
    "//src/gpu-compute:GPULDS",
    "//src/gpu-compute:GPUMem",
    "//src/gpu-compute:GPUPort",
    "//src/gpu-compute:GPUPrefetch",
    "//src/gpu-compute:GPUReg",
    "//src/gpu-compute:GPURF",
    "//src/gpu-compute:GPURFC",
    "//src/gpu-compute:GPURename",
    "//src/gpu-compute:GPURfState",
    "//src/gpu-compute:GPUSched",
    "//src/gpu-compute:GPUShader",
    "//src/gpu-compute:GPUSRF",
    "//src/gpu-compute:GPUSync",
    "//src/gpu-compute:GPUTLB",
    "//src/gpu-compute:GPUTrace",
    "//src/gpu-compute:GPUVRF",
    "//src/gpu-compute:GPUVRFSched",
    "//src/gpu-compute:GPUWgLatency",
    "//src/gpu-compute:Predictor",
    "//src/gpu-compute:WavefrontStack",

    # src/learning_gem5/part2
    "//src/learning_gem5/part2:HelloExample",
    "//src/learning_gem5/part2:SimpleCache",
    "//src/learning_gem5/part2:SimpleMemobj",

    # src/systemc
    "//src/systemc:TlmBridge",
]
