"""Rule for SLICC protocol compilation.

Compiles .slicc protocol definitions into C++ controller code and
SimObject Python files. Uses manifest-declared outputs when available
(generated by configure.bzl), falling back to tree artifacts when
manifests are empty or unavailable.

SLICC-generated code includes external types as "mem/ruby/protocol/<Type>.hh"
but the actual headers live in subdirectories (common/, structures/, etc.).
Forwarding headers are generated alongside SLICC output to redirect these
includes, matching CMake's _ruby_make_include() mechanism.

SLICC also generates controller SimObject .py files that must be fed
into the SimObject aggregate param generator. These are exposed via the
SliccInfo provider and extracted by _slicc_py_extract for downstream use.

For MULTIPLE-protocol builds, SLICC generates identical "shared" interface
types (enums, message types from RubySlicc_interfaces.slicc) for every
protocol. CMake deduplicates by tracking seen .cc files across protocols;
Bazel deduplicates by splitting each protocol's output into _shared (no
alwayslink, so linker picks one copy) and _unique (alwayslink, for
constructor retention). Shared files have no "/" in their manifest path;
protocol-specific files have a "Protocol/" prefix.
"""

load("@rules_cc//cc:defs.bzl", "cc_library")
load("//configs:slicc_manifests.bzl", "SLICC_MANIFESTS", "SLICC_PY_MANIFESTS")

# Provider to carry SLICC-generated .py files separately from .cc/.hh.
SliccInfo = provider(
    doc = "SLICC compilation outputs split by type.",
    fields = {
        "py_files": "depset of generated SimObject .py files",
    },
)

# Provider for shared/unique file split (used by MULTIPLE mode).
SliccSplitInfo = provider(
    doc = "SLICC outputs split into shared interface types and unique controllers.",
    fields = {
        "shared_srcs": "depset of shared .cc files (interface types)",
        "shared_hdrs": "depset of shared .hh files + forwarding headers",
        "unique_srcs": "depset of protocol-specific .cc files",
        "unique_hdrs": "depset of protocol-specific .hh files",
    },
)

# Forwarding headers for external types referenced by SLICC-generated code.
# Maps basename -> actual include path relative to mem/ruby/.
# Matches CMake's _ruby_make_include() calls in protocol/CMakeLists.txt.
_SLICC_FORWARDING_HEADERS = {
    "AbstractCacheEntry.hh": "slicc_interface/AbstractCacheEntry.hh",
    "Message.hh": "slicc_interface/Message.hh",
    "RubyRequest.hh": "slicc_interface/RubyRequest.hh",
    "Address.hh": "common/Address.hh",
    "BoolVec.hh": "common/BoolVec.hh",
    "DataBlock.hh": "common/DataBlock.hh",
    "ExpectedMap.hh": "common/ExpectedMap.hh",
    "IntVec.hh": "common/IntVec.hh",
    "MachineID.hh": "common/MachineID.hh",
    "NetDest.hh": "common/NetDest.hh",
    "TriggerQueue.hh": "common/TriggerQueue.hh",
    "Set.hh": "common/Set.hh",
    "WriteMask.hh": "common/WriteMask.hh",
    "MessageBuffer.hh": "network/MessageBuffer.hh",
    "CacheMemory.hh": "structures/CacheMemory.hh",
    "DirectoryMemory.hh": "structures/DirectoryMemory.hh",
    "PerfectCacheMemory.hh": "structures/PerfectCacheMemory.hh",
    "PersistentTable.hh": "structures/PersistentTable.hh",
    "RubyPrefetcher.hh": "structures/RubyPrefetcher.hh",
    "RubyPrefetcherProxy.hh": "structures/RubyPrefetcherProxy.hh",
    "TBEStorage.hh": "structures/TBEStorage.hh",
    "TBETable.hh": "structures/TBETable.hh",
    "TimerTable.hh": "structures/TimerTable.hh",
    "WireBuffer.hh": "structures/WireBuffer.hh",
    "DMASequencer.hh": "system/DMASequencer.hh",
    "Sequencer.hh": "system/Sequencer.hh",
    "GPUCoalescer.hh": "system/GPUCoalescer.hh",
    "HTMSequencer.hh": "system/HTMSequencer.hh",
    "VIPERCoalescer.hh": "system/VIPERCoalescer.hh",
    "VIPERSequencer.hh": "system/VIPERSequencer.hh",
    "MN_TBEStorage.hh": "structures/MN_TBEStorage.hh",
    "MN_TBETable.hh": "structures/MN_TBETable.hh",
}

def _forwarding_header_cmds(output_dir):
    """Generate shell commands to create forwarding headers in output_dir."""
    cmds = []
    for basename, subpath in _SLICC_FORWARDING_HEADERS.items():
        cmds.append(
            "printf '\\x23include \"mem/ruby/{subpath}\"\\n' > {dir}/{basename}".format(
                subpath = subpath,
                dir = output_dir,
                basename = basename,
            ),
        )
    return " && ".join(cmds)

def _find_file_by_suffix(files, suffix):
    """Find the first file in a list whose path ends with the given suffix."""
    for f in files:
        if f.path.endswith(suffix):
            return f
    return None

def _slicc_gen_impl(ctx):
    """Run SLICC to generate C++ and Python from protocol definitions."""
    src = ctx.file.src
    protocol = ctx.attr.protocol
    cc_manifest = SLICC_MANIFESTS.get(protocol, [])
    py_manifest = SLICC_PY_MANIFESTS.get(protocol, [])

    slicc_init = _find_file_by_suffix(ctx.files._slicc_files, "slicc/__init__.py")
    ply_init = _find_file_by_suffix(ctx.files._ply_files, "ply/__init__.py")
    grammar_file = _find_file_by_suffix(ctx.files._grammar_files, "grammar.py")

    # Resolve the protocol base directory for SLICC.
    # For most protocols, this is the .slicc file's directory.
    # For cross-directory protocols (e.g., MSI in learning_gem5/part3/),
    # _interfaces_slicc provides the interfaces file and its directory
    # is used as the protocol base so SLICC finds shared types.
    interfaces_file = None
    if ctx.file._interfaces_slicc:
        interfaces_file = ctx.file._interfaces_slicc

    script = ctx.actions.declare_file("_run_slicc_{}.py".format(ctx.label.name))
    ctx.actions.write(
        output = script,
        content = """\
import sys
import os

slicc_file = sys.argv[1]
code_output_dir = sys.argv[2]
slicc_init = sys.argv[3]
ply_init = sys.argv[4]
grammar_file = sys.argv[5]
interfaces_override = sys.argv[6] if len(sys.argv) > 6 else ""

# Set up import paths
slicc_parent = os.path.dirname(os.path.dirname(slicc_init))
sys.path.insert(0, slicc_parent)

ply_parent = os.path.dirname(os.path.dirname(ply_init))
sys.path.insert(0, ply_parent)

grammar_dir = os.path.dirname(grammar_file)
sys.path.insert(0, grammar_dir)

from slicc.parser import SLICC

os.makedirs(code_output_dir, exist_ok=True)

# Use interfaces override directory as protocol_base when provided,
# so SLICC finds shared types regardless of the .slicc file's location.
if interfaces_override:
    protocol_base = os.path.dirname(interfaces_override)
    interfaces_list = [interfaces_override]
else:
    protocol_base = os.path.dirname(slicc_file)
    # Find interfaces slicc file (may be in protocol_base or parent for
    # subdirectory protocols like CHI)
    interfaces_slicc = os.path.join(protocol_base, "RubySlicc_interfaces.slicc")
    if not os.path.exists(interfaces_slicc):
        interfaces_slicc = os.path.join(os.path.dirname(protocol_base), "RubySlicc_interfaces.slicc")
    interfaces_list = [interfaces_slicc] if os.path.exists(interfaces_slicc) else []

slicc = SLICC(slicc_file, interfaces_list, protocol_base)
slicc.process()
slicc.writeCodeFiles(code_output_dir, ["mem/ruby/slicc_interface/RubySlicc_includes.hh"])
""",
    )

    all_inputs = [src, script] + ctx.files.sm_sources + \
                 ctx.files._slicc_files + ctx.files._ply_files + \
                 ctx.files._grammar_files
    if interfaces_file:
        all_inputs.append(interfaces_file)
    interfaces_arg = interfaces_file.path if interfaces_file else ""

    if cc_manifest:
        # Manifest-based: declare individual output files.
        # Files go under mem/ruby/protocol/ within the slicc_ prefix
        # so #include "mem/ruby/protocol/X.hh" resolves correctly.
        prefix = "slicc_{}/mem/ruby/protocol".format(protocol)

        # Split manifest into shared (no "/" in path, from
        # RubySlicc_interfaces.slicc) and unique (Protocol/ prefixed).
        shared_cc_manifest = [f for f in cc_manifest if "/" not in f and f.endswith(".cc")]
        shared_hh_manifest = [f for f in cc_manifest if "/" not in f and f.endswith(".hh")]
        unique_cc_manifest = [f for f in cc_manifest if "/" in f and f.endswith(".cc")]
        unique_hh_manifest = [f for f in cc_manifest if "/" in f and f.endswith(".hh")]

        shared_cc_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in shared_cc_manifest]
        shared_hh_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in shared_hh_manifest]
        unique_cc_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in unique_cc_manifest]
        unique_hh_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in unique_hh_manifest]

        slicc_outputs = shared_cc_outputs + shared_hh_outputs + unique_cc_outputs + unique_hh_outputs

        # Also declare forwarding headers for external types.
        fwd_outputs = [
            ctx.actions.declare_file("{}/{}".format(prefix, basename))
            for basename in _SLICC_FORWARDING_HEADERS.keys()
        ]

        # Declare .py outputs for SimObject controller definitions.
        py_outputs = [ctx.actions.declare_file("{}/{}".format(prefix, f)) for f in py_manifest]

        all_outputs = slicc_outputs + fwd_outputs + py_outputs
        # Use forwarding header dirname for the protocol root directory.
        # Manifest entries may have protocol subdirectories (MESI_Two_Level/...)
        # but forwarding headers always go at the protocol root level.
        proto_root_dir = fwd_outputs[0].dirname

        ctx.actions.run_shell(
            outputs = all_outputs,
            inputs = all_inputs,
            command = "{fwd_cmds} && python3 {script} {src} {outdir} {slicc} {ply} {grammar} {iface}".format(
                fwd_cmds = _forwarding_header_cmds(proto_root_dir),
                script = script.path,
                src = src.path,
                outdir = proto_root_dir,
                slicc = slicc_init.path if slicc_init else "",
                ply = ply_init.path if ply_init else "",
                grammar = grammar_file.path if grammar_file else "",
                iface = interfaces_arg,
            ),
            mnemonic = "SLICC",
            progress_message = "Compiling SLICC protocol {} (manifest)".format(protocol),
        )

        return [
            DefaultInfo(files = depset(slicc_outputs + fwd_outputs)),
            SliccInfo(py_files = depset(py_outputs)),
            SliccSplitInfo(
                shared_srcs = depset(shared_cc_outputs),
                shared_hdrs = depset(shared_hh_outputs + fwd_outputs),
                unique_srcs = depset(unique_cc_outputs),
                unique_hdrs = depset(unique_hh_outputs),
            ),
        ]
    else:
        # Fallback: tree artifact for dynamic output when manifest is
        # unavailable (discovery not yet run or new protocol). Generated
        # .py files end up inside the tree artifact and cannot be passed
        # individually to SimObject param generation, so controller
        # params will be missing. This is acceptable for initial SLICC
        # compilation but a full build requires running slicc_discover.
        # buildifier: disable=print
        print("WARNING: SLICC protocol '{}' has no manifest; ".format(protocol) +
              "controller .py files will not be available for SimObject " +
              "param generation. Run 'bazel run //tools:slicc_discover' " +
              "to generate configs/slicc_manifests.bzl.")

        out_dir = ctx.actions.declare_directory("slicc_{}".format(protocol))
        nested_path = "{}/mem/ruby/protocol".format(out_dir.path)

        ctx.actions.run_shell(
            outputs = [out_dir],
            inputs = all_inputs,
            command = "mkdir -p {nested} && {fwd_cmds} && python3 {script} {src} {nested} {slicc} {ply} {grammar} {iface}".format(
                nested = nested_path,
                fwd_cmds = _forwarding_header_cmds(nested_path),
                script = script.path,
                src = src.path,
                slicc = slicc_init.path if slicc_init else "",
                ply = ply_init.path if ply_init else "",
                grammar = grammar_file.path if grammar_file else "",
                iface = interfaces_arg,
            ),
            mnemonic = "SLICC",
            progress_message = "Compiling SLICC protocol {} (tree)".format(protocol),
        )

        return [
            DefaultInfo(files = depset([out_dir])),
            SliccInfo(py_files = depset()),
            SliccSplitInfo(
                shared_srcs = depset(),
                shared_hdrs = depset(),
                unique_srcs = depset(),
                unique_hdrs = depset(),
            ),
        ]

_slicc_gen = rule(
    implementation = _slicc_gen_impl,
    attrs = {
        "src": attr.label(mandatory = True, allow_single_file = [".slicc"]),
        "protocol": attr.string(mandatory = True),
        "sm_sources": attr.label_list(
            allow_files = [".sm", ".slicc"],
            doc = "State machine and protocol files.",
        ),
        "_slicc_files": attr.label(
            default = "//src/mem/slicc:slicc_files",
            allow_files = True,
        ),
        "_ply_files": attr.label(
            default = "@gem5_ext_ply//:ply_files",
            allow_files = True,
        ),
        "_grammar_files": attr.label(
            default = "//build_tools:grammar_files",
            allow_files = True,
        ),
        "_interfaces_slicc": attr.label(
            default = "//src/mem/ruby/protocol:RubySlicc_interfaces.slicc",
            allow_single_file = [".slicc"],
            doc = "RubySlicc_interfaces.slicc for cross-directory protocols.",
        ),
    },
)

def _slicc_py_extract_impl(ctx):
    """Extract SLICC-generated .py files from SliccInfo provider."""
    slicc_info = ctx.attr.slicc_gen[SliccInfo]
    return [DefaultInfo(files = slicc_info.py_files)]

_slicc_py_extract = rule(
    implementation = _slicc_py_extract_impl,
    attrs = {
        "slicc_gen": attr.label(
            mandatory = True,
            providers = [SliccInfo],
        ),
    },
)

def _slicc_split_extract_impl(ctx):
    """Extract a specific file set from SliccSplitInfo provider."""
    split_info = ctx.attr.slicc_gen[SliccSplitInfo]
    files = getattr(split_info, ctx.attr.field)
    return [DefaultInfo(files = files)]

_slicc_split_extract = rule(
    implementation = _slicc_split_extract_impl,
    attrs = {
        "slicc_gen": attr.label(
            mandatory = True,
            providers = [SliccSplitInfo],
        ),
        "field": attr.string(
            mandatory = True,
            values = ["shared_srcs", "shared_hdrs", "unique_srcs", "unique_hdrs"],
        ),
    },
)

def gem5_slicc_protocol(name, src, protocol = None, sm_sources = [],
                        visibility = None, deps = [], copts = []):
    """Compile a SLICC protocol into C++ sources and SimObject .py files.

    Uses manifest-declared outputs when available (from configs/slicc_manifests.bzl),
    falling back to tree artifacts for protocols with empty or missing manifests.

    Creates these targets:
      {name}:         cc_library with ALL compiled SLICC C++ code (backward
                      compatible, used by single-protocol mode).
      {name}_shared:  cc_library with shared interface types only (no
                      alwayslink). In MULTIPLE mode, the linker picks one
                      copy and ignores duplicates from other protocols.
      {name}_unique:  cc_library with protocol-specific controllers only
                      (alwayslink for constructor retention).
      {name}_py:      Filegroup of generated SimObject .py files.

    Args:
        name: Target name (typically the protocol name).
        src: The main .slicc file.
        protocol: Protocol name. Defaults to name.
        sm_sources: State machine .sm files and included .slicc files.
        visibility: Visibility.
        deps: Dependencies for the generated cc_library.
        copts: Additional compiler flags.
    """
    if protocol == None:
        protocol = name

    gen_name = "_gen_slicc_{}".format(name)
    slicc_copts = copts + ["-Wno-unused-variable", "-DNUMBER_BITS_PER_SET=64"]
    slicc_includes = [".", "slicc_{}".format(name)]

    _slicc_gen(
        name = gen_name,
        src = src,
        protocol = protocol,
        sm_sources = sm_sources,
    )

    # Full protocol library (backward compatible, all files with alwayslink).
    # Used in single-protocol mode (via active_protocol alias).
    cc_library(
        name = name,
        srcs = [":{}".format(gen_name)],
        hdrs = [":{}".format(gen_name)],
        deps = deps + ["//src:gem5_hdrs"],
        copts = slicc_copts,
        includes = slicc_includes,
        visibility = visibility,
        alwayslink = True,
    )

    # Split targets for MULTIPLE mode deduplication.
    # Shared types are identical across all protocols (from
    # RubySlicc_interfaces.slicc). Without alwayslink, the linker links
    # only one copy when multiple protocols are combined.
    _slicc_split_extract(
        name = name + "_shared_srcs",
        slicc_gen = ":{}".format(gen_name),
        field = "shared_srcs",
    )

    _slicc_split_extract(
        name = name + "_shared_hdrs",
        slicc_gen = ":{}".format(gen_name),
        field = "shared_hdrs",
    )

    cc_library(
        name = name + "_shared",
        srcs = [":{}".format(name + "_shared_srcs")],
        hdrs = [":{}".format(name + "_shared_hdrs")],
        deps = deps + ["//src:gem5_hdrs"],
        copts = slicc_copts,
        includes = slicc_includes,
        visibility = visibility,
    )

    _slicc_split_extract(
        name = name + "_unique_srcs",
        slicc_gen = ":{}".format(gen_name),
        field = "unique_srcs",
    )

    _slicc_split_extract(
        name = name + "_unique_hdrs",
        slicc_gen = ":{}".format(gen_name),
        field = "unique_hdrs",
    )

    cc_library(
        name = name + "_unique",
        srcs = [":{}".format(name + "_unique_srcs")],
        hdrs = [":{}".format(name + "_unique_hdrs")],
        deps = deps + ["//src:gem5_hdrs", ":{}".format(name + "_shared")],
        copts = slicc_copts,
        includes = slicc_includes,
        visibility = visibility,
        alwayslink = True,
    )

    _slicc_py_extract(
        name = name + "_py",
        slicc_gen = ":{}".format(gen_name),
        visibility = visibility,
    )
