# Copyright (c) 2025 Akanksha Chaudhari, Matt Sinclair
# (University of Wisconsin-Madison)
# All rights reserved.
#
# This file contains modifications and/or code derived from:
# gem5-SALAM: https://github.com/TeCSAR-UNCC/gem5-SALAM
#
# The license below extends only to copyright in the software and shall
# not be construed as granting a license to any other intellectual
# property including but not limited to intellectual property relating
# to a hardware implementation of the functionality of the software
# licensed hereunder.  You may use the software subject to the license
# terms below provided that you ensure that this notice is replicated
# unmodified and in its entirety in all distributions of the software,
# modified or unmodified, in source code or in binary form.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')
if env['CONF']['USE_ARM_ISA'] and env['CONF'].get('WITH_SALAM', False):

    Source('add.cc')
    Source('addrspacecast.cc')
    Source('alloca.cc')
    Source('and_inst.cc')
    Source('ashr.cc')
    Source('bitcast.cc')
    Source('br.cc')
    Source('call.cc')
    Source('fadd.cc')
    Source('fcmp.cc')
    Source('fdiv.cc')
    Source('fence.cc')
    Source('fmul.cc')
    Source('fmuladd.cc')
    Source('fneg.cc')
    Source('fpext.cc')
    Source('fptosi.cc')
    Source('fptoui.cc')
    Source('fptrunc.cc')
    Source('frem.cc')
    Source('fsub.cc')
    Source('gep.cc')
    Source('icmp.cc')
    Source('indirectbr.cc')
    Source('inttoptr.cc')
    Source('invoke.cc')
    Source('landingpad.cc')
    Source('load.cc')
    Source('lshr.cc')
    Source('mul.cc')
    Source('or_inst.cc')
    Source('phi.cc')
    Source('ptrtoint.cc')
    Source('resume.cc')
    Source('ret.cc')
    Source('sdiv.cc')
    Source('select.cc')
    Source('sext.cc')
    Source('shl.cc')
    Source('srem.cc')
    Source('store.cc')
    Source('sub.cc')
    Source('switch_inst.cc')
    Source('trunc.cc')
    Source('udiv.cc')
    Source('uitofp.cc')
    Source('unreachable.cc')
    Source('urem.cc')
    Source('vaarg.cc')
    Source('xor_inst.cc')
    Source('zext.cc')
