# Copyright 2018 Google, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import gem5_scons

Import('*')

if env['CONF']['USE_SYSTEMC']:
    SimObject('SystemC.py', sim_objects=[
        'SystemC_Kernel', 'SystemC_ScObject', 'SystemC_ScModule'])

    Source('channel.cc')
    Source('event.cc')
    Source('kernel.cc')
    Source('messages.cc')
    Source('module.cc')
    Source('object.cc')
    Source('port.cc')
    Source('process.cc')
    Source('sched_event.cc')
    Source('sensitivity.cc')
    Source('time.cc')

    Source('sc_attr.cc')
    Source('sc_event.cc')
    Source('sc_export.cc')
    Source('sc_interface.cc')
    Source('sc_join.cc')
    Source('sc_main.cc')
    Source('sc_main_fiber.cc')
    Source('sc_module.cc')
    Source('sc_module_name.cc')
    Source('sc_object.cc')
    Source('sc_port.cc')
    Source('sc_process_handle.cc')
    Source('sc_prim.cc')
    Source('sc_sensitive.cc')
    Source('sc_simcontext.cc')
    Source('sc_spawn.cc')
    Source('sc_time.cc')

    if env['USE_PYTHON']:
        Source('python.cc')
        Source('sc_main_python.cc')
        append = {}
        with gem5_scons.Configure(env) as conf:
            for flag in ('-Wno-self-assign-overloaded', '-Wno-self-assign'):
                if conf.CheckCxxFlag(flag, autoadd=False):
                    append['CCFLAGS'] = [flag]
                    break
        Source('sc_time_python.cc', append=append)

    # Disable the false positive warning for the event members of the scheduler.
    with gem5_scons.Configure(env) as conf:
        flag = '-Wno-free-nonheap-object'
        append = {}
        if conf.CheckCxxFlag(flag, autoadd=False):
            append['CCFLAGS'] = [flag]
        Source('scheduler.cc', append=append)
