SST_VERSION=SST-14.0.0 # Name of the .pc file in lib/pkgconfig where SST is installed
GEM5_LIB=gem5_shared
ARCH=RISCV
OFLAG=3
GEM5_ROOT=../..
GEM5_BUILD_DIR=$(GEM5_ROOT)/build/$(ARCH)

LDFLAGS=-shared -fno-common ${shell pkg-config ${SST_VERSION} --libs} -L$(GEM5_BUILD_DIR)/ -Wl,-rpath $(GEM5_BUILD_DIR)
CXXFLAGS=-std=c++17 -g -O${OFLAG} -fPIC ${shell pkg-config ${SST_VERSION} --cflags} ${shell python3-config --includes} -I$(GEM5_ROOT)/src/ -I$(GEM5_BUILD_DIR)/generated/ -I$(GEM5_ROOT)/include/ -I$(GEM5_ROOT)/ext/pybind11/include/ -I$(GEM5_ROOT)/ext
CPPFLAGS+=-MMD -MP
SRC=$(wildcard *.cc)

.PHONY: clean all

all: libgem5.so

libgem5.so: $(SRC:%.cc=%.o)
	${CXX} ${CPPFLAGS} ${LDFLAGS} $? -o $@ -l${GEM5_LIB}

-include $(SRC:%.cc=%.d)

clean:
	${RM} *.[do] libgem5.so
