# -*- mode:python -*-

# Copyright (c) 2009 The University of Edinburgh
# Copyright (c) 2020 LabWare
# Copyright (c) 2021 IBM Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

if env['CONF']['USE_POWER_ISA']:
    env.TagImplies('power isa', 'gem5 lib')

Source('decoder.cc', tags='power isa')
Source('faults.cc', tags='power isa')
Source('insts/branch.cc', tags='power isa')
Source('insts/mem.cc', tags='power isa')
Source('insts/integer.cc', tags='power isa')
Source('insts/floating.cc', tags='power isa')
Source('insts/condition.cc', tags='power isa')
Source('insts/static_inst.cc', tags='power isa')
Source('linux/se_workload.cc', tags='power isa')
Source('isa.cc', tags='power isa')
Source('pagetable.cc', tags='power isa')
Source('process.cc', tags='power isa')
Source('remote_gdb.cc', tags='power isa')
Source('se_workload.cc', tags='power isa')
Source('tlb.cc', tags='power isa')

SimObject('PowerDecoder.py', sim_objects=['PowerDecoder'], tags='power isa')
SimObject('PowerInterrupts.py', sim_objects=['PowerInterrupts'],
    tags='power isa')
SimObject('PowerISA.py', sim_objects=['PowerISA'], tags='power isa')
SimObject('PowerMMU.py', sim_objects=['PowerMMU'], tags='power isa')
SimObject('PowerSeWorkload.py', sim_objects=[
    'PowerSEWorkload', 'PowerEmuLinux'], tags='power isa')
SimObject('PowerTLB.py', sim_objects=['PowerTLB'], tags='power isa')

SimObject('PowerCPU.py', sim_objects=[], tags='power isa')

DebugFlag('Power', tags='power isa')

ISADesc('isa/main.isa', tags='power isa')
