# cmake/Gem5ConfigHeaders.cmake
# Generate config/*.hh headers from Kconfig variables.
#
# In the SCons build, `env.ConfigFile(opt)` generates a header
# config/<opt_lowercase>.hh containing `#define <OPT> <value>`.
# This module replicates that by iterating over all CONF_* variables
# set by Gem5Kconfig.cmake.
#
# Headers are written at configure time to ${GEM5_GEN_DIR}/config/.

file(MAKE_DIRECTORY "${GEM5_GEN_DIR}/config")

# Helper function to generate one config header
function(_gem5_gen_config_header opt_name opt_value)
    # Convert name to lowercase for the filename
    string(TOLOWER "${opt_name}" _lower_name)
    set(_output "${GEM5_GEN_DIR}/config/${_lower_name}.hh")

    # Convert the value to the right C++ format
    if(opt_value STREQUAL "TRUE")
        set(_define_value "1")
    elseif(opt_value STREQUAL "FALSE" OR opt_value STREQUAL "")
        set(_define_value "0")
    elseif(opt_value MATCHES "^[0-9]+$" OR opt_value MATCHES "^0x[0-9a-fA-F]+$")
        set(_define_value "${opt_value}")
    else()
        # String value -- add quotes
        set(_define_value "\"${opt_value}\"")
    endif()

    gem5_write_if_unchanged("${_output}" "#define ${opt_name} ${_define_value}\n")
endfunction()

# Generate a config header for each CONF_* variable
# These come from the gem5_kconfig.cmake file generated by kconfig_to_cmake.py
get_cmake_property(_all_vars VARIABLES)
foreach(_var ${_all_vars})
    if(_var MATCHES "^CONF_(.+)$")
        set(_opt_name "${CMAKE_MATCH_1}")
        _gem5_gen_config_header("${_opt_name}" "${${_var}}")
    endif()
endforeach()

# Extra config headers not from Kconfig (detected during CMake configure)
_gem5_gen_config_header("HAVE_PERF_ATTR_EXCLUDE_HOST" "${HAVE_PERF_ATTR_EXCLUDE_HOST}")

# Also generate the_gpu_isa.hh (special config header from src/SConscript)
if(CONF_BUILD_GPU AND CONF_TARGET_GPU_ISA)
    set(_gpu_isa "${CONF_TARGET_GPU_ISA}")
    # Capitalize first letter for namespace name
    string(SUBSTRING "${_gpu_isa}" 0 1 _first)
    string(SUBSTRING "${_gpu_isa}" 1 -1 _rest)
    string(TOUPPER "${_first}" _first)
    string(TOLOWER "${_rest}" _rest)
    set(_namespace "${_first}${_rest}ISA")

    gem5_write_if_unchanged("${GEM5_GEN_DIR}/config/the_gpu_isa.hh"
        "#ifndef TheGpuISA\n#define TheGpuISA ${_namespace}\n#endif // TheGpuISA\n"
    )
else()
    gem5_write_if_unchanged("${GEM5_GEN_DIR}/config/the_gpu_isa.hh"
        "#ifndef TheGpuISA\n#define TheGpuISA None\n#endif // TheGpuISA\n"
    )
endif()

# Some config values are used in headers without an explicit #include of
# their config header (e.g., NUMBER_BITS_PER_SET in Set.hh). Provide
# these as compile definitions so they're available everywhere.
if(CONF_NUMBER_BITS_PER_SET)
    add_compile_definitions(NUMBER_BITS_PER_SET=${CONF_NUMBER_BITS_PER_SET})
endif()

message(STATUS "Generated config headers in ${GEM5_GEN_DIR}/config/")
