#!/usr/bin/env python3
"""
kconfig_to_cmake.py -- Bridge gem5 Kconfig to CMake variables.

Reads a Kconfig tree (src/Kconfig) with a defconfig file
(build_opts/<variant>) using ext/Kconfiglib, and outputs a .cmake file
containing CONF_* variables for use by the CMake build system.

The Kconfig files use $(VARIABLE) macros that are resolved from environment
variables at parse time.  CMake passes detected dependency results as
-D KEY=VALUE arguments so this script can set them before loading Kconfig.

Usage:
    python3 kconfig_to_cmake.py \
        --kconfig src/Kconfig \
        --defconfig build_opts/X86 \
        --output build/gem5_kconfig.cmake \
        -D HAVE_FENV=y -D HAVE_PNG=y ...
"""

import argparse
import os
import sys


def main():
    parser = argparse.ArgumentParser(
        description="Convert gem5 Kconfig defconfig to CMake variables"
    )
    parser.add_argument(
        "--kconfig", required=True, help="Path to top-level Kconfig file"
    )
    parser.add_argument(
        "--defconfig", required=True,
        help="Path to defconfig file (build_opts/<variant>)"
    )
    parser.add_argument(
        "--output", required=True, help="Path to output .cmake file"
    )
    parser.add_argument(
        "-D", action="append", dest="defines", default=[],
        help="Environment variables for Kconfig macros (KEY=VALUE)"
    )
    args = parser.parse_args()

    # Add ext/Kconfiglib/import to the Python path so we can import kconfiglib.
    # The gem5 tree stores kconfiglib.py under ext/Kconfiglib/import/.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    kconfiglib_import_dir = os.path.join(
        project_root, "ext", "Kconfiglib", "import"
    )

    if os.path.isdir(kconfiglib_import_dir):
        sys.path.insert(0, kconfiglib_import_dir)
    else:
        # Fallback: try the Kconfiglib root, then system-installed
        kconfiglib_dir = os.path.join(project_root, "ext", "Kconfiglib")
        if os.path.isdir(kconfiglib_dir):
            sys.path.insert(0, kconfiglib_dir)

    try:
        import kconfiglib
    except ImportError:
        print(
            "ERROR: Cannot import kconfiglib. "
            "Ensure ext/Kconfiglib exists or install kconfiglib via pip.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Set CONFIG_ prefix to empty string, matching gem5's SCons convention
    os.environ["CONFIG_"] = ""

    # Set environment variables passed via -D flags.
    # These are needed by Kconfig $(VARIABLE) macros such as $(HAVE_FENV).
    for define in args.defines:
        if "=" in define:
            key, val = define.split("=", 1)
        else:
            key, val = define, "y"
        os.environ[key] = val

    # Load the Kconfig tree
    try:
        kconf = kconfiglib.Kconfig(filename=args.kconfig, warn=False)
    except Exception as e:
        print(f"ERROR: Failed to load Kconfig: {e}", file=sys.stderr)
        sys.exit(1)

    # Load the defconfig
    try:
        kconf.load_config(args.defconfig)
    except Exception as e:
        print(f"ERROR: Failed to load defconfig: {e}", file=sys.stderr)
        sys.exit(1)

    # Generate CMake output
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    with open(args.output, "w") as f:
        f.write("# Auto-generated by kconfig_to_cmake.py\n")
        f.write(f"# Variant: {os.path.basename(args.defconfig)}\n")
        f.write(f"# Kconfig: {args.kconfig}\n")
        f.write("# Do not edit manually.\n\n")

        for sym in kconf.unique_defined_syms:
            name = sym.name
            val = sym.str_value
            cmake_name = f"CONF_{name}"

            if sym.type == kconfiglib.BOOL:
                cmake_val = "TRUE" if val == "y" else "FALSE"
                f.write(f'set({cmake_name} {cmake_val})\n')
            elif sym.type == kconfiglib.TRISTATE:
                cmake_val = "TRUE" if val == "y" else "FALSE"
                f.write(f'set({cmake_name} {cmake_val})\n')
            elif sym.type == kconfiglib.INT:
                cmake_val = val if val else "0"
                f.write(f'set({cmake_name} {cmake_val})\n')
            elif sym.type == kconfiglib.HEX:
                cmake_val = val if val else "0"
                f.write(f'set({cmake_name} 0x{cmake_val})\n')
            elif sym.type == kconfiglib.STRING:
                f.write(f'set({cmake_name} "{val}")\n')
            else:
                # Unknown type -- store as string
                f.write(f'set({cmake_name} "{val}")\n')

        f.write("\n# End of generated Kconfig variables\n")

    print(f"Generated {args.output} with {len(kconf.unique_defined_syms)} symbols")


if __name__ == "__main__":
    main()
