load("@rules_cc//cc:defs.bzl", "cc_library")


cc_library(
    name = "magic_enum",
    hdrs = ["magic_enum.hh"],
    includes = [".."],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
