---
# This workflow runs all of the very-long tests within TestLib.

name: Weekly Tests

on:
    # This is triggered weekly via the 'scheduler.yaml' workflow.
    workflow_dispatch:

jobs:

    get-testlib-very-long-dirs:
        runs-on: ubuntu-24.04
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        outputs:
            test-dirs-matrix: ${{ steps.dir-matrix.outputs.test-dirs-matrix }}
        steps:
            - uses: actions/checkout@v7
            - name: Get directories for testlib-very-long
              id: dir-matrix
              run: |
                  python3 util/ci/testlib.py discover --length very-long > "$RUNNER_TEMP/test-plan.json"
                  echo "test-dirs-matrix=$(jq -c '.directories' "$RUNNER_TEMP/test-plan.json")" >> "$GITHUB_OUTPUT"
    # start running the very-long tests
    testlib-very-long-tests:
        name: very-long-tests
        strategy:
            fail-fast: false
            max-parallel: 5
            matrix:
                test-type: ${{ fromJson(needs.get-testlib-very-long-dirs.outputs.test-dirs-matrix) }}
        runs-on: [self-hosted, linux, x64]
        container:
            image: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
            volumes:
                - /gem5-resource-cache:/gem5-resource-cache
        env:
            GEM5_RESOURCE_DIR: /gem5-resource-cache
        timeout-minutes: 4320 # 3 days
        needs: [get-testlib-very-long-dirs]
        steps:
            - uses: actions/checkout@v7

            - name: Run very-long ${{ matrix.test-type }} tests
              id: run-tests
              timeout-minutes: 4290
              env:
                  TEST_DIR: ${{ matrix.test-type }}
              run: python3 util/ci/testlib.py run --directory "$TEST_DIR" --length very-long --jobs "$(nproc)"
            - name: Sanitize test-dir for artifact name
              id: sanitize-test-dir
              if: always()
              run: echo "sanitized-test-dir=$(echo '${{ matrix.test-type }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT

            - name: Upload results
              if: always()
              uses: actions/upload-artifact@v7
              with:
                  name: weekly-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-testlib-very-long-${{ steps.sanitize-test-dir.outputs.sanitized-test-dir
                      }}-status-${{ steps.run-tests.outcome }}-output
                  path: tests/testing-results
